const p=app.plugins.plugins['qiaomu-cover-design'],wait=ms=>new Promise(r=>setTimeout(r,ms)),assert=(x,m)=>{if(!x)throw Error(m)},until=async fn=>{for(let i=0;i<150&&!fn();i++)await wait(20);assert(fn(),'Timed out')};
const original=p.settings.assistant,language=p.settings.language,inputs=[];const unregister=p.registerAssistant({id:'polish-regression',name:'Polish regression',run:async input=>{inputs.push(structuredClone(input));return {reply:'已按要求换色',ops:[{op:'recolor',target:'title',color:'#ffff00'}]}}});
try{
 p.settings.assistant='polish-regression';p.settings.language='zh';await p.ensureFolder(p.settings.designFolder);
 const file=await app.vault.create(p.unique(p.settings.designFolder,'Chat polish regression '+Date.now(),'qcover'),JSON.stringify(p.initialDesign('minimal','保留指定颜色','回归测试',undefined,'xhs')));await p.openDesign(file);const v=p.activeCover();await until(()=>v.canvas&&!v.restoring);await app.workspace.revealLeaf(v.leaf);
 await v.ask('把标题改为黄色');await wait(60);const title=v.canvas.getObjects().find(o=>o.qcRole==='title');assert(title.fill==='#ffff00','Chosen yellow overridden');assert(v.chat.at(-1).warn?.some(s=>s.includes('对比度')),'Low contrast warning missing');assert(v.chat.at(-1).suggestions.some(s=>s.id==='contrast:stroke'),'No repair suggestion');
 const user=v.contentEl.querySelector('.qc-msg-user'),next=user.nextElementSibling,actions=user.querySelector('.qc-msg-controls'),a=actions.getBoundingClientRect(),b=next.getBoundingClientRect();assert(a.bottom<=b.top,'User actions overlap next reply');
 const fix=v.contentEl.querySelector('.qc-fix'),style=getComputedStyle(fix),root=getComputedStyle(fix.closest('.qc-root'));assert(style.color!==root.getPropertyValue('--interactive-accent').trim(),'Repair uses host accent');assert(!v.contentEl.querySelector('.qc-conversation-new').hasAttribute('aria-label'),'New button creates redundant hover tip');
 const yellow=v.snapshot();await v.runThumbSuggestion('contrast:stroke');assert(title.fill==='#ffff00'&&title.strokeWidth>0&&title.stroke,'Outline loses chosen hue');await v.restoreSnapshot(yellow);await v.runThumbSuggestion('contrast:deepen');const dark=v.canvas.getObjects().find(o=>o.qcRole==='title');assert(dark.fill!=='#ffff00','Deepen did not change colour');
 const before=JSON.stringify(v.currentDesign());v.currentPattern='deleted-context';v.lastSpec={title:'deleted-state'};await v.deleteTurn(0);assert(v.chat.length===0&&!v.currentPattern&&!v.lastSpec,'Deleted turn state survives');assert(JSON.stringify(v.currentDesign())===before,'Delete turn changes artwork');await v.ask('标题改为黄色');assert(inputs.at(-1).history.length===0,'Deleted exchange leaks provider context');
 // Delete a middle exchange with multiple replies; unrelated exchanges survive.
 v.chat=[{role:'user',text:'keep first'},{role:'assistant',text:'first done'},{role:'user',text:'remove middle'},{role:'assistant',text:'middle done'},{role:'assistant',text:'middle note'},{role:'user',text:'keep last'},{role:'assistant',text:'last done'}];await v.deleteTurn(3);assert(v.chat.map(m=>m.text).join('|')==='keep first|first done|keep last|last done','Delete exchange range incorrect');
 // Saving may yield; a reply must not be retried into a switched conversation.
 v.chat=[{role:'user',text:'old failed request'},{role:'assistant',text:'failed',failed:true}];const save=v.saveChatNow.bind(v),ask=v.ask.bind(v);let release,saveStarted=false,calls=0;v.saveChatNow=async()=>{saveStarted=true;await new Promise(r=>release=r)};v.ask=async()=>{calls++};const retry=v.retryTurn(1);await until(()=>saveStarted);const active=v.conversationBook.active;v.conversationBook.active='changed-during-save';release();await retry;assert(calls===0,'Retry crossed conversation boundary');v.conversationBook.active=active;v.saveChatNow=save;v.ask=ask;await v.saveChatNow();
 return {chosenColourKept:true,warningAndRepairs:true,actionsDoNotOverlap:true,neutralRepair:true,quietAccessibleIcons:true,deleteContextAndCanvasSafe:true,middleExchangeDeletion:true,retryIsolation:true,file:file.path};
}finally{unregister();p.settings.assistant=original;p.settings.language=language;await p.saveSettings()}
