// Real designer UI and provider boundary. Uses an injected provider; no paid request or private canvas is touched.
const p=app.plugins.plugins['qiaomu-cover-design'],wait=ms=>new Promise(r=>setTimeout(r,ms)),assert=(x,m)=>{if(!x)throw Error(m);},until=async fn=>{for(let i=0;i<200&&!fn();i++)await wait(20);assert(fn(),'Timed out');};
const oldAssistant=p.settings.assistant,oldLanguage=p.settings.language,inputs=[];let release;
const unregister=p.registerAssistant({id:'conversation-qa',name:'Conversation QA',run:async input=>{inputs.push(structuredClone(input));await new Promise(r=>{release=r;});return {reply:'蓝色方案已应用',ops:[{op:'recolor',target:'title',color:'#2563eb'}]};}});
try{
 p.settings.language='zh';p.settings.assistant='conversation-qa';await p.ensureFolder(p.settings.designFolder);
 const path=p.unique(p.settings.designFolder,'对话隔离 QA '+Date.now(),'qcover'),f=await app.vault.create(path,JSON.stringify(p.initialDesign('minimal','保留的作品','原有副标题',undefined,'xhs')));
 p.settings.chats[path]=[{role:'user',text:'旧对话：一切改为绿色'},{role:'assistant',text:'旧绿色方案'}];await p.saveSettings();await p.openDesign(f);await wait(150);
 const v=app.workspace.getLeavesOfType('qiaomu-cover-design').find(l=>l.view.file?.path===path).view;await until(()=>!v.restoring);await app.workspace.revealLeaf(v.leaf);
 assert(v.chat[0].text.includes('旧对话'),'Legacy chat not migrated');const legacyId=v.activeConversation.id;const before=JSON.stringify(v.currentDesign());
 const input=()=>v.contentEl.querySelector('.qc-chat-input');input().value='旧对话草稿';input().dispatchEvent(new Event('input',{bubbles:true}));v.currentPattern='stale-pattern';v.lastSpec={title:'stale-title'};v.lastPrompt='stale request';
 const button=v.contentEl.querySelector('.qc-conversation-new'),bar=v.contentEl.querySelector('.qc-conversation-bar'),br=button.getBoundingClientRect(),rr=bar.getBoundingClientRect();assert(br.height===28&&br.left>=rr.left&&br.right<=rr.right,'Conversation toolbar geometry');button.click();button.click();await until(()=>v.conversations.length===2);await until(()=>input().value==='');
 assert(v.chat.length===0&&v.assistantInput('新的要求').history.length===0,'Old chat leaked into fresh context');assert(!v.currentPattern&&!v.lastSpec&&!v.lastPrompt,'Hidden old turn state survived');assert(JSON.stringify(v.currentDesign())===before,'New chat modified artwork');
 const freshId=v.activeConversation.id;await v.switchConversation(legacyId);assert(input().value==='旧对话草稿','Draft lost on switch');assert(JSON.stringify(v.currentDesign())===before,'History switch modified artwork');await v.switchConversation(freshId);
 const running=v.ask('将标题改成蓝色');await until(()=>inputs.length===1);assert(v.contentEl.querySelector('.qc-conversation-new').disabled&&v.contentEl.querySelector('.qc-conversation-title').disabled,'Busy navigation not disabled');await v.newChat();assert(v.activeConversation.id===freshId,'Busy request switched conversations');
 input().value='完成后继续缩小标题';input().dispatchEvent(new Event('input',{bubbles:true}));release();await running;assert(inputs[0].history.length===0&&!inputs[0].pattern,'Fresh provider input included old chat');assert(inputs[0].canvas.some(x=>x.text?.replace(/\s/g,'')==='保留的作品'),'Current canvas not supplied');assert(v.canvas.getObjects().find(o=>o.qcRole==='title').fill==='#2563eb','Provider result not applied');
 const messageIndex=v.chat.length-1,snapshot=v.chat[messageIndex].snapshot;assert(snapshot&&v.contentEl.querySelector('.qc-msg-more'),'Message direction entry missing');
 const title=v.canvas.getObjects().find(o=>o.qcRole==='title');v.canvas.setActiveObject(title);await wait(30);assert(v.contentEl.querySelector('.qc-chat-scope').textContent.replace(/\s/g,'').includes('保留的作品'),'Selection scope not visible');v.contentEl.querySelector('.qc-chat-scope-clear').click();assert(!v.selection().length&&v.contentEl.querySelector('.qc-chat-scope-name').textContent==='当前画布','Scope deselection failed');
 await v.newChat();const emptyId=v.activeConversation.id;assert(v.chat.length===0,'Second new chat inherited messages');await v.switchConversation(freshId);assert(input().value==='完成后继续缩小标题','Busy typing draft lost');
 const menuItem=text=>[...document.querySelectorAll('.menu-item')].find(e=>e.querySelector('.menu-item-title')?.textContent===text);
 const openMenu=async()=>{const b=v.contentEl.querySelector('.qc-conversation-title'),r=b.getBoundingClientRect();b.dispatchEvent(new MouseEvent('click',{bubbles:true,clientX:r.left+8,clientY:r.bottom}));await until(()=>menuItem(v.t('chatRename')));};
 await openMenu();menuItem(v.t('chatRename')).click();await until(()=>document.querySelector('.modal-content.qc-modal input'));const rename=document.querySelector('.modal-content.qc-modal input');rename.value='蓝色方向';[...document.querySelectorAll('.modal-content.qc-modal button')].find(b=>b.textContent===v.t('save')).click();await until(()=>v.activeConversation.title==='蓝色方向');await until(()=>!document.querySelector('.modal-content.qc-modal input'));assert(v.contentEl.querySelector('.qc-conversation-name').textContent==='蓝色方向','Rename header stale');
 await v.switchConversation(emptyId);await openMenu();menuItem(v.t('chatDelete')).click();await until(()=>document.querySelector('.modal-content.qc-modal'));const buttons=[...document.querySelectorAll('.modal-content.qc-modal button')];buttons.find(b=>b.textContent===v.t('cancel')).click();assert(v.conversations.length===3,'Cancel deleted history');await openMenu();menuItem(v.t('chatDelete')).click();await wait(30);[...document.querySelectorAll('.modal-content.qc-modal button')].find(b=>b.textContent===v.t('remove')).click();await until(()=>v.conversations.length===2);assert(v.canvas.getObjects().find(o=>o.qcRole==='title').fill==='#2563eb','Delete changed artwork');
 await v.switchConversation(freshId);title.set({fill:'#e11d2e'});v.changed();await v.flush();const original=await app.vault.read(f);await v.branchConversation(messageIndex);await wait(150);
 const branch=p.activeCover();assert(branch&&branch.file.path!==f.path,'Direction did not create separate canvas');assert(branch.canvas.getObjects().find(o=>o.qcRole==='title').fill==='#2563eb','Direction ignored selected turn snapshot');assert(await app.vault.read(f)===original,'Direction changed original canvas');assert(branch.chat.length===2,'Direction context crossed chosen message');const branchPath=branch.file.path;
 await branch.blankConversation();await wait(150);const blank=p.activeCover();assert(blank.file.path!==branchPath&&blank.canvas.getObjects().length===0&&blank.design.width===1080&&blank.design.height===1440,'Blank start not isolated or wrong size');
 await app.fileManager.renameFile(f,f.path.replace('.qcover',' renamed.qcover'));assert(!p.settings.conversations[path]&&p.settings.conversations[f.path],'Canvas rename lost conversation index');await v.saveChatNow();
 window.__qcConversationQA={file:f.path,branch:branchPath,blank:blank.file.path,freshId,legacyId,expectedDraft:'完成后继续缩小标题'};
 return {legacyMigration:true,newChatCanvasKept:true,rapidClickDeduplicated:true,providerContextIsolated:true,hiddenStateReset:true,busyNavigationLocked:true,draftsPreserved:true,scopeDeselect:true,rename:true,deleteCancel:true,deleteCanvasKept:true,branchUsesTurnSnapshot:true,branchOriginalUnchanged:true,blankSeparate:true,canvasRenameKeepsHistory:true,files:window.__qcConversationQA};
}finally{release?.();unregister();p.settings.assistant=oldAssistant;p.settings.language=oldLanguage;await p.saveSettings();}
