const p=app.plugins.plugins['qiaomu-cover-design'],wait=ms=>new Promise(r=>setTimeout(r,ms)),assert=(x,m)=>{if(!x)throw Error(m);};
document.querySelectorAll('.modal-header-button').forEach(e=>e.click());
const file=await p.createDesign('连续画笔 QA '+Date.now(),'minimal',undefined,'画笔验收','xhs');await wait(180);const v=app.workspace.getLeavesOfType('qiaomu-cover-design').find(l=>l.view.file?.path===file.path).view;for(let i=0;v.restoring&&i<100;i++)await wait(20);v.canvas.clear();v.changed();await v.flush();v.setZoom(.55);
try {
const pen=v.containerEl.querySelector('.qc-draw-btn'),gallery=v.containerEl.querySelector('.qc-gallery-trigger'),shape=v.containerEl.querySelector('.qc-insert-shape');assert(shape.nextElementSibling===pen&&pen.nextElementSibling===gallery,'Pen/gallery toolbar order incorrect');pen.click();assert(v.canvas.isDrawingMode&&pen.getAttribute('aria-pressed')==='true','Drawing mode did not start');assert(!document.querySelector('.qc-draw-popover'),'Brush popup should not exist');
const options=v.containerEl.querySelector('.qc-draw-bar');assert(!options.hidden,'Inline brush bar missing');const width=options.querySelector('input[type=number]');width.value='12';width.dispatchEvent(new Event('input',{bubbles:true}));options.querySelector('[data-color="#2563eb"]').click();assert(options.querySelector('[data-color="#2563eb"]').getAttribute('aria-pressed')==='true','Active color not visible');
const draw=(offset,id=90,dot=false)=>{const z=v.canvas.getZoom(),r=v.canvas.upperCanvasEl.getBoundingClientRect(),emit=(type,x,y,target,samples)=>{const e=new PointerEvent(type,{bubbles:true,cancelable:true,button:0,buttons:type==='pointerup'?0:1,clientX:r.left+x*z,clientY:r.top+y*z,pointerId:id,pointerType:'mouse',pressure:.5});if(samples)Object.defineProperty(e,'getCoalescedEvents',{value:()=>samples.map(([a,b])=>new PointerEvent('pointermove',{clientX:r.left+a*z,clientY:r.top+b*z,pressure:.5}))});target.dispatchEvent(e);};emit('pointerdown',150,200+offset,v.canvas.upperCanvasEl);if(!dot){emit('pointermove',320,200+offset,document,[[170,220+offset],[220,180+offset],[270,220+offset],[320,200+offset]]);emit('pointermove',-180,200+offset,document,[[100,200+offset],[-30,200+offset],[-90,200+offset],[-180,200+offset]]);emit('pointermove',350,240+offset,document);}emit('pointerup',dot?150:350,dot?200+offset:240+offset,document);};
draw(0);draw(150,91);draw(300,92,true);assert(v.canvas.getObjects().length===3,'Continuous drawing/marquee/dot failed');const strokes=v.canvas.getObjects();assert(strokes.every(s=>s.type.toLowerCase()==='path'&&s.qcName==='笔迹'&&s.fill==='#2563eb'),'Stroke metadata/style missing');assert(strokes[0].left<0&&strokes[0].width>350,'Outside samples were discarded');assert(strokes[2].width>=10&&strokes[2].width<=14,'Dot width incorrect');
await v.flush();await v.travel(-1);assert(v.canvas.getObjects().length===2,'Undo dot failed');await v.travel(-1);assert(v.canvas.getObjects().length===1,'Quick strokes merged in undo');await v.travel(1);await v.travel(1);assert(v.canvas.getObjects().length===3,'Redo failed');
const r=v.canvas.upperCanvasEl.getBoundingClientRect();v.canvas.upperCanvasEl.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,cancelable:true,button:0,pointerId:93,pointerType:'pen',clientX:r.left+150,clientY:r.top+100,pressure:.8}));window.dispatchEvent(new Event('blur'));assert(v.canvas.getObjects().length===4,'Lost focus dropped a stroke');
v.stage.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(!v.canvas.isDrawingMode&&options.hidden&&pen.getAttribute('aria-pressed')==='false','Escape did not exit drawing');v.canvas.setActiveObject(v.canvas.getObjects()[0]);v.refreshInspector(true);assert(v.containerEl.querySelector('.qc-inspector .qc-color'),'Stroke not editable');
await v.flush();const saved=JSON.parse(await app.vault.read(file));assert(saved.canvas.objects.length===4,'Strokes not saved');assert(v.getIcon()==='qiaomu-cover-image'&&document.querySelector('.side-dock-ribbon .clickable-icon svg path'),'Plugin icon not registered');
pen.click();const remote=require('@electron/remote'),win=remote.BrowserWindow.getAllWindows().find(w=>w.getTitle()===document.title),fs=require('fs');await wait(100);fs.writeFileSync('/tmp/qcover-drawing-wide.png',(await win.webContents.capturePage()).toPNG());
const body=document.body,wasDark=body.classList.contains('theme-dark');body.toggleClass('theme-dark',!wasDark);body.toggleClass('theme-light',wasDark);await wait(50);fs.writeFileSync('/tmp/qcover-drawing-dark.png',(await win.webContents.capturePage()).toPNG());body.toggleClass('theme-dark',wasDark);body.toggleClass('theme-light',!wasDark);
const center=v.containerEl.querySelector('.qc-center'),old=center.style.maxWidth;center.style.maxWidth='360px';await wait(50);assert(options.scrollWidth<=options.clientWidth+2,'Brush bar overflows at narrow width');fs.writeFileSync('/tmp/qcover-drawing-narrow.png',(await win.webContents.capturePage()).toPNG());center.style.maxWidth=old;
pen.click();assert(!v.canvas.isDrawingMode&&options.hidden,'Second click should exit, not reopen popup');return {continuous:true,coalesced:true,outsideReturn:true,dot:true,colorWidth:true,toolbarOrder:true,strokeUndoRedo:true,blur:true,escape:true,editable:true,saved:true,narrow:true,icon:true,file:file.path};

} finally { v.setDrawing(false); }
