const p=app.plugins.plugins['qiaomu-cover-design'];
if(!p)throw new Error('Plugin missing');
const folder='QCover QA';if(!app.vault.getAbstractFileByPath(folder))await app.vault.createFolder(folder);
const path=`${folder}/Note-${Date.now()}.md`;const note=await app.vault.create(path,'# 封面设计验收\n\n正文保留。\n');
const file=await p.createDesign('QCover QA '+Date.now(),'editorial',note,'让想法\n成为封面');
const view=app.workspace.getLeavesOfType('qiaomu-cover-design').find(l=>l.view.file?.path===file.path).view;
await new Promise(r=>setTimeout(r,250));
const count=view.canvas.getObjects().length;
view.addText();view.addShape('circle');await view.flush();
if(view.canvas.getObjects().length!==count+2)throw new Error('Add failed');
await view.travel(-1);if(view.canvas.getObjects().length!==count+1)throw new Error('Undo failed');
await view.travel(1);if(view.canvas.getObjects().length!==count+2)throw new Error('Redo failed');
await view.flush();const saved=JSON.parse(await app.vault.read(file));
const output=await view.exportPng(true);const binary=await app.vault.readBinary(output);
const bytes=new Uint8Array(binary);const pngWidth=new DataView(binary).getUint32(16);const pngHeight=new DataView(binary).getUint32(20);
if(bytes[0]!==137||pngWidth!==960||pngHeight!==1280)throw new Error('PNG dimensions wrong');
if(!(await app.vault.read(note)).includes(output.basename))throw new Error('Embed missing');
const home=p.qiaomuHome.sections();if(!home[0].items.some(i=>i.id===file.path))throw new Error('Home missing');
return {version:p.manifest.version,file:file.path,objects:saved.canvas.objects.length,png:output.path,bytes:binary.byteLength,pngWidth,pngHeight,embed:true,home:true,buttons:view.contentEl.querySelectorAll('button').length};
