const p=app.plugins.plugins['qiaomu-cover-design'];p.settings.language='zh';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const folder='QCover QA';if(!app.vault.getAbstractFileByPath(folder))await app.vault.createFolder(folder);
const note=await app.vault.create(`${folder}/N-${Date.now()}.md`,'# 笔记\n\n正文。\n');
const file=await p.createDesign('功能 '+Date.now(),'bold',note,'让想法\n成为封面','xhs');
await wait(700);
const v=app.workspace.getLeavesOfType('qiaomu-cover-design').map(l=>l.view).find(x=>x.file?.path===file.path);
const out={};
v.setPlatform('youtube');await wait(100);
out.afterPlatform=[v.design.width,v.design.height,v.canvas.getObjects().every(o=>o.left>=-1&&o.left<v.design.width)];
v.applyTemplate('dark');await wait(150);out.tpl=v.canvas.getObjects().length;out.title=v.copyText().title;
const r=await p.assistantList()[0].run({prompt:'背景改成深蓝渐变，标题放大，文字居中',zh:true,fonts:['PingFang SC'],size:{width:1280,height:720}});
out.ops=r.ops.map(o=>o.op);
v.canvas.setActiveObject(v.canvas.getObjects().find(o=>o.qcRole==='title'));
out.applied=await v.runAssistantOps(r.ops);
await p.fonts.scanSystem(document);
await v.setFont('PingFang SC');out.font=v.canvas.getObjects().find(o=>o.qcRole==='title').fontFamily;
const fs=require('fs');const cand=['/System/Library/Fonts/Supplemental/Georgia.ttf','/System/Library/Fonts/Supplemental/Arial.ttf'].find(f=>fs.existsSync(f));
if(cand){const f=new File([fs.readFileSync(cand)],'QA Test Font.ttf');out.imported=await p.fonts.importFiles([f],document);out.vaultFonts=p.fonts.vault.map(x=>x.family);await v.setFont('QA Test Font');out.avail=p.fonts.available(document,'QA Test Font');}
const base=v.exportPrefs();
const png=await v.exportWith({...base,format:'png',scale:2,insert:true,cover:true,filename:'{name}-{platform}-{size}'});out.png=png.path;
const b=new DataView(await app.vault.readBinary(png));out.pngSize=[b.getUint32(16),b.getUint32(20)];
const jpg=await v.exportWith({...base,format:'jpeg',quality:0.8,destination:'note',filename:'x'});out.jpg=jpg.path;
out.note=(await app.vault.read(note)).slice(0,220);
out.sys=await v.exportWith({...base,format:'webp',destination:'system',systemDir:'~/Downloads/qcover-qa'});
const before=v.canvas.getObjects().length;v.addShape('star');await v.flush();await v.travel(-1);out.undo=v.canvas.getObjects().length===before;
await v.flush();const raw=await app.vault.read(file);const saved=JSON.parse(raw);out.saved=[saved.platform,saved.bg?.kind,saved.canvas.objects.length,saved.export.format,raw.length];
v.canvas.discardActiveObject();v.refreshInspector(true);
return out;
