// Library acceptance uses isolated owned fixtures. No real model request is made.
const p=app.plugins.plugins['qiaomu-cover-design'],wait=ms=>new Promise(r=>setTimeout(r,ms)),assert=(x,m)=>{if(!x)throw Error(m);},results={};
assert(p.gallery,'Gallery not loaded');document.querySelectorAll('.modal-header-button').forEach(e=>e.click());
const file=await p.createDesign('图库验收 '+Date.now(),'minimal',undefined,'图库验收','xhs');await wait(250);const v=app.workspace.getLeavesOfType('qiaomu-cover-design').find(l=>l.view.file?.path===file.path).view;for(let i=0;v.restoring&&i<100;i++)await wait(20);
const c=document.createElement('canvas');c.width=160;c.height=100;c.getContext('2d').fillStyle='#8acdb4';c.getContext('2d').fillRect(0,0,160,100);const blob=await new Promise(r=>c.toBlob(r,'image/png')),buffer=await blob.arrayBuffer();
const fs=require('fs'),path=require('path'),folder=fs.mkdtempSync(path.join(require('os').tmpdir(),'qcover-gallery-host-'));fs.writeFileSync(path.join(folder,'folder-test.png'),Buffer.from(buffer));fs.writeFileSync(path.join(folder,'folder-second.png'),Buffer.from(buffer));fs.writeFileSync(path.join(folder,'folder-third.png'),Buffer.from(buffer));fs.writeFileSync(path.join(folder,'ignored.txt'),'QA');
let calls=0;const job=await p.imageJobs.submit({prompt:'图库测试提示词',model:'Gallery fixture',path:file.path,layers:false,request:{modelId:p.settings.ai.imageId,width:160,height:100,options:{}}},async()=>{calls++;return {pictures:[{data:buffer,type:'image/png',name:'图库测试生成 A'},{data:buffer,type:'image/png',name:'图库测试生成 B'}],warnings:[]};});for(let i=0;job.state!=='ready'&&i<100;i++)await wait(20);assert(job.state==='ready','Fixture job unfinished');
const savedFolders=structuredClone(p.settings.galleryFolders),remote=require('@electron/remote'),originalDialog=remote.dialog.showOpenDialog;
const modal=()=>document.querySelector('.qc-gallery-modal'),tab=id=>modal().querySelector(`[data-tab="${id}"]`).click(),btn=(label,within=modal())=>Array.from(within.querySelectorAll('button')).find(b=>b.textContent.trim()===label),close=()=>modal()?.querySelector('.modal-header-button').click();
try{
 const tools=v.containerEl.querySelector('.qc-header-create');assert(!tools.querySelector('.qc-insert-other')&&tools.querySelector('.qc-insert-shape'),'Toolbar still has More or lacks Shapes');assert(v.containerEl.querySelector('.qc-gallery-trigger svg'),'Gallery icon unavailable');
 v.containerEl.querySelector('.qc-gallery-trigger').click();await wait(250);assert(getComputedStyle(modal().querySelector('.modal-title')).position==='absolute','Gallery title is still visible');assert(modal()&&modal().querySelectorAll('[role=tab]').length===4,'Four library tabs missing');assert(modal().querySelectorAll('[title]').length===0,'Native duplicate tips in Gallery');
 const uploadName=`gallery-upload-${Date.now()}.png`;const files=new DataTransfer();files.items.add(new File([blob],uploadName,{type:'image/png'}));const upload=modal().querySelector('input[type=file]');upload.files=files.files;upload.dispatchEvent(new Event('change',{bubbles:true}));await wait(250);for(let i=0;!Array.from(modal().querySelectorAll('.qc-gallery-name')).some(e=>e.textContent===uploadName)&&i<100;i++)await wait(20);assert(Array.from(modal().querySelectorAll('.qc-gallery-name')).some(e=>e.textContent===uploadName),'Custom upload failed');const image=(await p.gallery.list()).find(i=>i.name===uploadName);assert(image.width===160&&image.height===100,'Upload dimensions incorrect');results.upload=true;
 for(let i=0;!modal().querySelector(`[data-id="upload:${image.id}"]`)&&i<150;i++)await wait(20);const manage=modal().querySelector(`[data-id="upload:${image.id}"] button[aria-label="管理图片"]`);manage.click();await wait(700);const menu=document.querySelector('.menu');assert(menu?.isConnected,'Gallery management menu closed prematurely');Array.from(menu.querySelectorAll('.menu-item')).find(e=>e.textContent.includes('重命名')).click();const rename=Array.from(document.querySelectorAll('.modal')).find(m=>m.querySelector('.modal-title')?.textContent==='重命名');rename.querySelector('input').value='gallery-renamed.png';btn('保存',rename).click();await wait(150);assert((await p.gallery.list()).find(i=>i.id===image.id).name==='gallery-renamed.png','Rename did not persist');results.renameMenu=true;

 tab('folders');await wait(70);remote.dialog.showOpenDialog=async()=>({canceled:false,filePaths:[folder]});btn('添加文件夹').click();await wait(200);assert(modal().querySelectorAll('.qc-gallery-tile').length===3,'Folder did not exclude non-images');modal().querySelector('.qc-gallery-card').click();results.folder=true;
 const hiddenName=modal().querySelector('.qc-gallery-name').textContent;const hide=modal().querySelector('button[aria-label="管理图片"]');hide.click();Array.from(document.querySelector('.menu').querySelectorAll('.menu-item')).find(e=>e.textContent.includes('从图库隐藏')).click();const hideConfirm=Array.from(document.querySelectorAll('.modal')).find(m=>m.querySelector('.modal-title')?.textContent==='从图库隐藏这张图片？');btn('确认隐藏',hideConfirm).click();await wait(150);assert(modal().querySelectorAll('.qc-gallery-tile').length===2&&fs.existsSync(path.join(folder,'folder-test.png')),'Folder hide changed originals or kept the image visible');assert(p.settings.galleryFolders.find(f=>f.path===folder).hidden.includes(hiddenName),'Hidden state was not saved');btn('已隐藏 1 张').click();const restore=Array.from(document.querySelectorAll('.modal')).find(m=>m.querySelector('.modal-title')?.textContent==='已隐藏的图片');btn('恢复全部 1 张',restore).click();await wait(130);assert(modal().querySelector('.qc-gallery-tile'),'Folder restoration failed');modal().querySelectorAll('.qc-gallery-card').forEach(e=>e.click());modal().querySelector('.qc-gallery-delete').click();const bulk=Array.from(document.querySelectorAll('.modal')).find(m=>m.querySelector('.modal-title')?.textContent==='隐藏选中的 3 张本地图片？');btn('确认隐藏',bulk).click();await wait(150);assert(!modal().querySelector('.qc-gallery-tile'),'Bulk hiding failed');btn('已隐藏 3 张').click();const allRestore=Array.from(document.querySelectorAll('.modal')).find(m=>m.querySelector('.modal-title')?.textContent==='已隐藏的图片');btn('恢复全部 3 张',allRestore).click();await wait(150);assert(modal().querySelectorAll('.qc-gallery-tile').length===3&&fs.existsSync(path.join(folder,'folder-second.png')),'Bulk restore changed originals');modal().querySelector('.qc-gallery-card').click();results.folderHideRestore=true;results.bulkHideRestore=true;

 tab('images');await wait(180);const uploadTile=Array.from(modal().querySelectorAll('.qc-gallery-tile')).find(t=>t.dataset.id===`upload:${image.id}`);uploadTile.querySelector('.qc-gallery-card').click();const gen=modal().querySelector(`[data-id="job:${job.id}:0"]`);assert(gen,'Generated image absent');gen.querySelector('.qc-gallery-card').click();assert(modal().querySelector('.qc-gallery-count').textContent==='已选 3 张','Selection across tabs lost');
 const before=v.canvas.getObjects().length;btn('插入画布').click();for(let i=0;modal()&&i<100;i++)await wait(25);assert(!modal()&&v.canvas.getObjects().length===before+3,'Batch insertion failed');await v.flush();await v.travel(-1);assert(v.canvas.getObjects().length===before,'Batch insertion did not undo as one operation');await v.travel(1);assert(v.canvas.getObjects().length===before+3,'Batch insertion redo failed');results.batchUndoRedo=true;
 p.openGallery('tasks',v);await wait(150);const task=modal().querySelector(`[data-job="${job.id}"]`);assert(task,'Task not in list');btn('编辑再生成',task).click();await wait(150);assert(!modal()&&document.querySelector('.qc-image-prompt')?.value===job.prompt,'Edit task did not prefill prompt');assert(calls===1,'Edit automatically called paid model');document.querySelector('.qc-image-generate-modal .modal-header-button').click();results.editWithoutCharge=true;
 p.openGallery('tasks',v);await wait(120);modal().querySelector(`[data-job="${job.id}"] button[aria-label="删除任务记录"]`).click();const confirm=Array.from(document.querySelectorAll('.modal')).find(m=>m.querySelector('.modal-title')?.textContent==='删除任务记录？');assert(confirm,'Task deletion confirmation missing');btn('确认删除',confirm).click();await wait(120);assert(job.taskDeleted&&!modal().querySelector(`[data-job="${job.id}"]`),'Task still in list');tab('images');await wait(120);assert(modal().querySelector(`[data-id="job:${job.id}:0"]`),'Deleting task lost generated pictures');results.recordKeepsImages=true;
 tab('unsplash');await wait(60);for(let i=0;modal().querySelector('.qc-gallery-status').textContent.includes('正在搜索')&&i<200;i++)await wait(40);results.unsplashRecommended=modal().querySelectorAll('.qc-gallery-tile').length>0;assert(results.unsplashRecommended,'Unsplash did not load recommended images');results.unsplashSetup=!!modal().querySelector('.qc-empty-title')||!!modal().querySelector('.qc-gallery-search');
 tab('images');await wait(120);await wait(300);assert(modal().querySelector('.qc-gallery-card img[src]'),'Lazy thumbnails did not load');
 const win=remote.BrowserWindow.getAllWindows().find(w=>w.getTitle()===document.title);fs.writeFileSync('/tmp/qcover-gallery-wide.png',(await win.webContents.capturePage()).toPNG());
 const oldWidth=modal().style.width;modal().style.width='370px';await wait(70);assert(modal().querySelector('.qc-gallery-body').scrollWidth<=modal().querySelector('.qc-gallery-body').clientWidth+2,'Gallery body overflows at narrow size');results.narrow=true;fs.writeFileSync('/tmp/qcover-gallery-narrow.png',(await win.webContents.capturePage()).toPNG());modal().style.width=oldWidth;
 const theme=document.body.classList.contains('theme-dark');document.body.removeClass(theme?'theme-dark':'theme-light');document.body.addClass(theme?'theme-light':'theme-dark');await wait(80);fs.writeFileSync('/tmp/qcover-gallery-dark.png',(await win.webContents.capturePage()).toPNG());document.body.removeClass(theme?'theme-light':'theme-dark');document.body.addClass(theme?'theme-dark':'theme-light');results.dark=true;
 const tile=modal().querySelector(`[data-id="upload:${image.id}"]`);tile.querySelector('button[aria-label="管理图片"]').click();const delMenu=document.querySelector('.menu');Array.from(delMenu.querySelectorAll('.menu-item')).find(e=>e.textContent.includes('删除图片')).click();const remove=Array.from(document.querySelectorAll('.modal')).find(m=>m.querySelector('.modal-title')?.textContent==='删除这张图片？');btn('确认删除',remove).click();await wait(150);assert(!fs.existsSync(path.join(app.vault.adapter.getBasePath(),p.manifest.dir,'gallery',image.id)),'Deleting upload retained library binary');assert(fs.existsSync(path.join(folder,'folder-test.png')),'Folder original was changed');results.imageDeletion=true;
 return {results,calls,jobId:job.id,file:file.path,unsplashConfigured:!!p.settings.unsplashSecret||!!p.settings.unsplashProxy};
}finally{if(job.state==='ready'){if(!job.taskDeleted)await p.imageJobs.removeRecord(job);while(job.pictures?.length)await p.imageJobs.removePicture(job,0);}remote.dialog.showOpenDialog=originalDialog;p.settings.galleryFolders=savedFolders;await p.saveSettings();close();fs.rmSync(folder,{recursive:true,force:true});}
