const p=app.plugins.plugins['qiaomu-cover-design'],wait=ms=>new Promise(r=>setTimeout(r,ms)),assert=(x,m)=>{if(!x)throw Error(m);},results={};document.querySelectorAll('.modal-header-button').forEach(e=>e.click());const file=await p.createDesign('批量删除 QA '+Date.now(),'minimal',undefined,'批量删除','xhs');await wait(180);const v=app.workspace.getLeavesOfType('qiaomu-cover-design').find(l=>l.view.file?.path===file.path).view;for(let i=0;v.restoring&&i<100;i++)await wait(20);
const c=document.createElement('canvas');c.width=160;c.height=100;c.getContext('2d').fillStyle='#adcef4';c.getContext('2d').fillRect(0,0,160,100);const data=await (await new Promise(r=>c.toBlob(r,'image/png'))).arrayBuffer(),a=await p.gallery.add('batch-owned-a.png','image/png',data,160,100),b=await p.gallery.add('batch-owned-b.png','image/png',data,160,100);
const result={pictures:[0,1,2].map(i=>({data,type:'image/png',width:160,height:100,name:'batch-generated-'+i})),warnings:[]},job=await p.imageJobs.submit({prompt:'Bulk delete owned fixture',model:'Gallery fixture',path:file.path,layers:false},async()=>result);for(let i=0;job.state!=='ready'&&i<100;i++)await wait(20);assert(job.state==='ready','Owned fixture failed');await v.applyImageResult([result.pictures[0]],undefined,false,v.imageGuard());await v.flush();const canvasBefore=JSON.stringify(v.canvas.toJSON());
const fs=require('fs'),path=require('path'),folder=fs.mkdtempSync(path.join(require('os').tmpdir(),'qcover-bulk-')),savedFolders=structuredClone(p.settings.galleryFolders),f={id:crypto.randomUUID(),name:'Bulk folder fixture',path:folder};for(const n of ['one.png','two.png'])fs.writeFileSync(path.join(folder,n),Buffer.from(data));p.settings.galleryFolders.push(f);await p.saveSettings();
const modal=()=>document.querySelector('.qc-gallery-modal'),btn=(t,el=document)=>Array.from(el.querySelectorAll('button')).find(b=>b.textContent.trim()===t),confirm=()=>Array.from(document.querySelectorAll('.modal')).find(m=>m.querySelector('.modal-title')?.textContent.startsWith('删除选中的')||m.querySelector('.modal-title')?.textContent.startsWith('隐藏选中的'));
try{
 p.openGallery('images',v);await wait(180);const trash=modal().querySelector('.qc-gallery-delete');assert(trash.disabled&&!modal().querySelector('.qc-gallery-clear'),'No-selection delete/clear replacement incorrect');for(const id of [`upload:${a.id}`,`upload:${b.id}`,`job:${job.id}:0`,`job:${job.id}:1`])modal().querySelector(`[data-id="${id}"] .qc-gallery-card`).click();assert(!trash.disabled&&modal().querySelector('.qc-gallery-count').textContent==='已选 4 张','Batch selection/delete disabled');trash.click();assert(confirm().querySelector('.modal-title').textContent.includes('4'),'Confirm count missing');btn('取消',confirm()).click();assert(job.pictures.length===3&&(await p.gallery.list()).some(x=>x.id===a.id),'Cancel deleted images');results.cancel=true;
 trash.click();btn('确认删除',confirm()).click();await wait(260);assert(job.pictures.length===1&&job.pictures[0].storageIndex===2&&job.pictures[0].name==='batch-generated-2','Batch deleted wrong sibling');assert(!fs.existsSync(path.join(app.vault.adapter.getBasePath(),p.manifest.dir,'gallery',a.id))&&!fs.existsSync(path.join(app.vault.adapter.getBasePath(),p.manifest.dir,'gallery',b.id)),'Upload files not removed');assert(fs.existsSync(path.join(app.vault.adapter.getBasePath(),p.manifest.dir,'image-jobs',job.id,'2.image')),'Unselected generated image removed');assert(!fs.existsSync(path.join(app.vault.adapter.getBasePath(),p.manifest.dir,'image-jobs',job.id,'0.image'))&&!fs.existsSync(path.join(app.vault.adapter.getBasePath(),p.manifest.dir,'image-jobs',job.id,'1.image')),'Selected generated binaries retained');assert(JSON.stringify(v.canvas.toJSON())===canvasBefore,'Deleting gallery changed canvas copies');assert(modal().querySelector('.qc-gallery-delete').disabled&&modal().querySelector(`[data-id="job:${job.id}:2"]`),'Selection not cleared or survivor absent');results.bulkDeletion=true;results.sameJobIndices=true;results.canvasCopyPreserved=true;
 const remote=require('@electron/remote'),w=remote.BrowserWindow.getAllWindows().find(w=>w.getTitle()===document.title);fs.writeFileSync('/tmp/qcover-gallery-bulk.png',(await w.webContents.capturePage()).toPNG());
 modal().querySelector('[data-tab=folders]').click();await wait(120);const select=modal().querySelector('select');select.value=f.id;select.dispatchEvent(new Event('change',{bubbles:true}));await wait(120);modal().querySelectorAll('.qc-gallery-card').forEach(b=>b.click());modal().querySelector('.qc-gallery-delete').click();assert(confirm().querySelector('.modal-title').textContent.includes('隐藏'),'Local removal warning wrong');btn('确认隐藏',confirm()).click();await wait(180);assert(!modal().querySelector('.qc-gallery-card')&&f.hidden?.length===2&&fs.existsSync(path.join(folder,'one.png'))&&fs.existsSync(path.join(folder,'two.png')),'Local batch delete changed originals');results.localHideOnly=true;
 return {results,file:file.path,job:job.id};
}finally{document.querySelector('.qc-gallery-modal .modal-header-button')?.click();for(const image of [a,b])if((await p.gallery.list()).some(x=>x.id===image.id))await p.gallery.remove(image);while(job.pictures?.length)await p.imageJobs.removePicture(job,0);await p.imageJobs.removeRecord(job);p.settings.galleryFolders=savedFolders;await p.saveSettings();fs.rmSync(folder,{recursive:true,force:true});}
