// Real UI model discovery, upload replacement, compact layout and reusable results; no generation POST.
const p=app.plugins.plugins['qiaomu-cover-design'],wait=ms=>new Promise(r=>setTimeout(r,ms)),assert=(x,m)=>{if(!x)throw Error(m);};
document.querySelectorAll('.qc-image-generate-modal .modal-header-button,.qc-image-preview-modal .modal-header-button').forEach(b=>b.click());const v=app.workspace.getLeavesOfType('qiaomu-cover-design').find(l=>l.view.canvas&&l.view.containerEl.getBoundingClientRect().width>0)?.view??p.activeCover();assert(v?.canvas,'Need active canvas');v.imageDialog?.close();v.openImageGenerator();await wait(50);let el=v.imageDialog.contentEl;
assert(el.querySelector('.qc-image-controls').compareDocumentPosition(el.querySelector('.qc-image-prompt'))&Node.DOCUMENT_POSITION_FOLLOWING,'Prompt before model');assert(!el.querySelector('.qc-image-options').closest('details').open,'Advanced not folded');
const ark=p.settings.ai.images.find(x=>x.snap.imageEngine==='ark'&&x.snap.imageModel==='doubao-seedream-5-0-260128');assert(ark,'Lite profile missing');const select=el.querySelector('.qc-image-model');select.value=ark.id;select.dispatchEvent(new Event('change'));const upload=el.querySelector('input[type=file]');assert(getComputedStyle(upload).display==='none','Native file input visible');assert(getComputedStyle(el.querySelector('.qc-image-upload')).display!=='none','Custom reference button missing');assert(getComputedStyle(el.querySelector('.qc-image-options select').parentElement).display==='none','Known version field visible');
const ai=v.containerEl.querySelector('.qc-ai-image-btn'),insert=v.containerEl.querySelector('.qc-insert-text');const gap=insert.getBoundingClientRect().left-ai.getBoundingClientRect().right;assert(gap>=9,'Toolbar buttons cramped');
// The model input stays specific while all seven candidates remain selectable.
el.querySelector('.qc-image-add-model').click();await wait(20);const gallery=document.querySelector('.qc-model-dialog');[...gallery.querySelectorAll('.qc-md-card')].find(c=>c.querySelector('.qc-md-card-name')?.textContent==='自定义').click();await wait(20);
const modelEl=document.querySelector('.qc-model-dialog'),profile=p.settings.ai.images.find(x=>x.snap.imageModel==='jimeng-4.5');assert(profile,'Jimeng profile missing');modelEl.querySelector('input[type=password]').value=profile.snap.imageKey;modelEl.querySelector('.qc-md-adv input').value=profile.snap.imageBaseUrl;const model=modelEl.querySelector('.qc-md-model-id');model.value='jimeng-4.5';model.dispatchEvent(new Event('input'));[...modelEl.querySelectorAll('button')].find(b=>b.textContent==='获取可用模型').click();for(let i=0;modelEl.querySelector('.qc-md-fetch button').disabled&&i<300;i++)await wait(20);
const picker=modelEl.querySelector('.qc-md-model-picker'),ids=[...picker.options].map(o=>o.value).filter(Boolean);assert(ids.length===7&&ids.includes('jimeng-5.0')&&ids.includes('jimeng-3.0'),'Seven model dropdown absent');assert(model.value==='jimeng-4.5','Fetch reset manual value');picker.value='jimeng-5.0';picker.dispatchEvent(new Event('change'));assert(model.value==='jimeng-5.0','Dropdown selection not applied');[...modelEl.querySelectorAll('button')].find(b=>b.textContent==='取消').click();
// Screenshot never includes the credential form.
el=v.imageDialog.contentEl;const capture=async(name)=>{await wait(50);const win=require('@electron/remote').getCurrentWindow();require('fs').writeFileSync(name,(await win.webContents.capturePage()).toPNG());};
await capture('/tmp/qcover-new-image-dialog.png');const modal=el.closest('.modal');modal.style.width='390px';await wait(50);assert(el.scrollWidth<=el.clientWidth+2,'Narrow dialog horizontal overflow');await capture('/tmp/qcover-new-image-dialog-narrow.png');modal.style.width='';v.imageDialog.close();
p.openImageTasks();await wait(40);const job=[...p.imageJobs.jobs.values()].find(j=>/jimeng/i.test(j.model)&&j.path.startsWith('Cover designs/即梦后台生图验收 ' )&&j.state==='ready'&&j.pictures?.length===4);assert(job?.state==='ready','Real Jimeng result lost');const row=[...document.querySelectorAll('.qc-image-task')].find(r=>r.querySelector('.qc-image-task-prompt')?.textContent===job.prompt);row.querySelector('button').click();for(let i=0;!document.querySelector('.qc-image-result-card')&&i<100;i++)await wait(20);const resultEl=document.querySelector('.qc-image-result-actions').closest('.qc-image-generate');assert(resultEl.querySelectorAll('.qc-image-result-card').length===4,'Four result cards missing');const card=resultEl.querySelector('.qc-image-result-card');assert(getComputedStyle(card).borderTopWidth==='1px','Result card border missing');assert(getComputedStyle(card.querySelector('.qc-image-result-check')).display==='flex','Selected indicator missing');resultEl.querySelector('.qc-image-expand').click();await wait(50);await document.querySelector('.qc-image-large-preview').decode();assert(document.querySelector('.qc-image-large-preview').naturalWidth===1728,'Large preview missing native image');document.querySelector('.qc-image-preview-modal .modal-header-button').click();await capture('/tmp/qcover-new-image-results.png');document.querySelector('.qc-image-generate-modal .modal-header-button').click();
return {modelCandidates:ids,manualModelPreserved:true,dropdownSelection:true,uploadHidden:true,customReferenceButton:true,advancedFolded:true,narrowNoOverflow:true,toolbarGap:gap,resultCount:4,largePreview:true};
