// Real Fabric grouping, selection, naming, transforms, undo and persisted hierarchy.
const p=app.plugins.plugins['qiaomu-cover-design'],wait=ms=>new Promise(r=>setTimeout(r,ms)),assert=(x,m)=>{if(!x)throw Error(m);};
const oldFile=p.activeCover()?.file,file=await p.createDesign('图层管理 QA '+Date.now(),'minimal',undefined,'图层','xhs');await wait(200);const v=app.workspace.getLeavesOfType('qiaomu-cover-design').find(l=>l.view.file?.path===file.path).view;for(let i=0;v.restoring&&i<100;i++)await wait(20);
v.canvas.clear();const a=v.addShape('rect');a.set({left:150,top:200,width:90,height:65,scaleX:1.2,scaleY:.8,angle:17});a.qcName='标题底板';a.setCoords();const b=v.addShape('circle');b.set({left:330,top:250,radius:40,scaleX:1,scaleY:1});b.qcName='角标';b.setCoords();const other=v.addShape('rect');other.qcName='背景';v.canvas.discardActiveObject();v.changed();await v.flush();
v.rightTab='layers';v.refreshInspector(true);const row=name=>[...v.containerEl.querySelectorAll('.qc-layer')].find(r=>r.querySelector('.qc-layer-name')?.textContent===name);
row('标题底板').click();row('角标').dispatchEvent(new MouseEvent('click',{bubbles:true,ctrlKey:true}));assert(v.canvas.getActiveObjects().length===2,'Layer multiselect failed');
const world=o=>o.calcTransformMatrix(),near=(a,b)=>a.every((n,i)=>Math.abs(n-b[i])<.001),before=[world(a),world(b)];v.groupLayers();const group=v.canvas.getActiveObject();assert(group.qcLayerGroup&&group.getObjects().length===2,'Group did not retain children');assert(near(before[0],world(a))&&near(before[1],world(b)),'Group shifted world coordinates');v.renameLayers([group],'标题组件');assert(row('标题组件'),'Group name absent');
const search=v.containerEl.querySelector('.qc-layer-search');search.value='角标';search.dispatchEvent(new Event('input'));assert(row('标题组件')&&row('角标')&&!row('背景'),'Hierarchical search failed');search.value='';search.dispatchEvent(new Event('input'));
// Native nested selections must not remove children from the owning group.
row('标题底板').click();row('角标').dispatchEvent(new MouseEvent('click',{bubbles:true,ctrlKey:true}));assert(v.canvas.getActiveObjects().length===2,'Nested multiselect failed');v.canvas.discardActiveObject();assert(group.getObjects().length===2,'Nested selection damaged group');v.canvas.setActiveObject(group);
group.set({angle:31,scaleX:1.4,scaleY:.7});group.setCoords();v.changed();const moved=group.getObjects().map(world);v.ungroupLayers();v.canvas.discardActiveObject();assert(v.canvas.getObjects().length===3,'Ungroup lost objects');assert(near(moved[0],world(a))&&near(moved[1],world(b)),'Ungroup changed transformed geometry');await v.undo();assert(v.canvas.getObjects().some(o=>o.qcName==='标题组件'&&o.qcLayerGroup),'Ungroup not one undo');await v.redo();assert(v.canvas.getObjects().length===3,'Ungroup redo failed');
// Batch naming persisted; stable assistant ids are independent.
const named=v.canvas.getObjects().filter(o=>o.qcName!=='背景');v.renameLayers(named,'内容');assert(named.map(o=>o.qcName).join(',')==='内容 1,内容 2','Batch naming failed');await v.flush();await v.onLoadFile(file);for(let i=0;v.restoring&&i<100;i++)await wait(20);assert(v.canvas.getObjects().filter(o=>o.qcName?.startsWith('内容')).length===2,'Layer names lost on reopen');
v.rightTab='layers';v.refreshInspector(true);row('内容 1').click();row('内容 2').dispatchEvent(new MouseEvent('click',{bubbles:true,ctrlKey:true}));v.groupLayers();v.renameLayers([v.canvas.getActiveObject()],'可编辑组件');await v.flush();await v.onLoadFile(file);for(let i=0;v.restoring&&i<100;i++)await wait(20);const restored=v.canvas.getObjects().find(o=>o.qcName==='可编辑组件');assert(restored?.qcLayerGroup&&restored.getObjects().length===2,'Hierarchy lost on reopen');v.rightTab='layers';v.refreshInspector(true);row('内容 1').click();const child=restored.getObjects().find(o=>o.qcName==='内容 1'),childMatrix=world(child);await v.cloneSelection();const copy=v.canvas.getActiveObject();assert(near(childMatrix.slice(0,4),world(copy).slice(0,4)),'Nested clone transform changed');assert(Math.abs(world(copy)[4]-childMatrix[4]-28)<.01,'Nested clone position changed');v.removeSelection();v.canvas.setActiveObject(child);v.removeSelection();assert(restored.getObjects().length===1,'Nested delete failed');await v.undo();assert(v.canvas.getObjects().find(o=>o.qcName==='可编辑组件').getObjects().length===2,'Nested deletion undo failed');await v.flush();v.rightTab='layers';v.refreshInspector(true);
let c=v.canvas;v.layerQuery='';v.rightTab='layers';v.refreshInspector(true);
row('内容 1').click();row('内容 2').dispatchEvent(new MouseEvent('click',{ctrlKey:true,bubbles:true}));const selectedSnapshot=JSON.stringify(v.currentDesign().canvas);c.discardActiveObject();assert(selectedSnapshot===JSON.stringify(v.currentDesign().canvas),'Nested selection changed serialized transforms');
row('背景').click();row('可编辑组件').dispatchEvent(new MouseEvent('click',{ctrlKey:true,bubbles:true}));v.groupLayers();const outer=c.getActiveObject(),inner=outer.getObjects().find(o=>o.qcLayerGroup);outer.set({scaleX:.8,scaleY:1.3,angle:21});outer.setCoords();v.changed();const matrices=inner.getObjects().map(o=>o.calcTransformMatrix());c.setActiveObject(inner);v.ungroupLayers();c.discardActiveObject();assert(outer.getObjects().length===3,'Nested ungroup failed');assert(outer.getObjects().filter(o=>o.qcName.startsWith('内容')).every((o,i)=>o.calcTransformMatrix().every((x,j)=>Math.abs(x-matrices[i][j])<.001)),'Nested ungroup changed world coordinates');await v.undo();c=v.canvas;assert(c.getObjects()[0].getObjects().some(o=>o.qcLayerGroup),'Nested ungroup undo failed');await v.redo();c=v.canvas;await v.flush();
// Same-parent reorder must immediately reflect in the layer tree.
v.rightTab='layers';v.refreshInspector(true);const reorderA=row('内容 1'),reorderB=row('内容 2'),data=new DataTransfer();reorderA.dispatchEvent(new DragEvent('dragstart',{dataTransfer:data,bubbles:true}));reorderB.dispatchEvent(new DragEvent('drop',{dataTransfer:data,bubbles:true,cancelable:true}));const displayed=[...v.containerEl.querySelectorAll('.qc-layer-name')].map(n=>n.textContent),actual=[...c.getObjects()[0].getObjects()].reverse().map(o=>o.qcName);assert(displayed.slice(1).join('|')===actual.join('|'),'Reorder tree stale');
return {file:file.path,nestedSerialization:true,nestedUngroup:true,nestedUndoRedo:true,treeReorder:true,multiSelect:true,editableGroup:true,nestedSelection:true,nestedCloneAndDelete:true,groupTransformPreserved:true,ungroupUndoRedo:true,batchNames:true,searchHierarchy:true,savedHierarchy:true};
