// Real-host fixture for reviewed reference edits and atomic raster/layer insertion; no paid requests.
const p=app.plugins.plugins['qiaomu-cover-design']; const wait=ms=>new Promise(r=>setTimeout(r,ms)); const assert=(value,message)=>{if(!value)throw Error(message);};
const original=p.activeCover()?.file,language=p.settings.language,settings=JSON.stringify(p.settings.ai); const proto=Object.getPrototypeOf(p.ai),images=proto.images;
const file=await p.createDesign('Seedream 编辑 QA '+Date.now(),'highlight',undefined,'原图编辑验证','xhs');await wait(300);
let v=app.workspace.getLeavesOfType('qiaomu-cover-design').find(l=>l.view.file?.path===file.path).view;for(let i=0;v.restoring&&i<50;i++)await wait(100);
const picture=async(w,h,color)=>{const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').fillStyle=color;c.getContext('2d').fillRect(0,0,w,h);const b=await new Promise(r=>c.toBlob(r,'image/png'));return {data:await b.arrayBuffer(),type:'image/png'};};
const pic=await picture(400,300,'#bd8450'),edit=await picture(800,450,'#52654e'); const results={};let resolve;
try{
 await v.applyImageResult([pic],undefined,false,v.imageGuard());const target=v.canvas.getActiveObject();target.set({left:123,top:234,angle:17,scaleX:.7,scaleY:.8,flipX:true,cropX:20,cropY:10,width:350,height:260});target.setCoords();v.changed();v.commitHistory();await v.flush();
 const n=v.canvas.getObjects().length,at=v.canvas.getObjects().indexOf(target),guard=v.imageGuard(target),geometry={left:target.left,top:target.top,angle:target.angle,width:target.getScaledWidth(),height:target.getScaledHeight(),flip:target.flipX};
 p.settings.ai.images.push({id:'seedream-host-fixture',snap:{imageOn:true,imageEngine:'ark',imageBaseUrl:'https://fixture.invalid',imageKey:'fixture',imageModel:'doubao-seedream-5-0-pro-260628',imageSize:'auto'}});v.imageModelId='seedream-host-fixture';
 proto.images=function(prompt,w,h,options){assert(options.references.length===1,'Original image not sent');assert(options.references[0].url.startsWith('data:image/png;base64,'),'Reference is not embedded raster');assert(options.references[0].width===400&&options.references[0].height===300,'Cropped canvas sent instead of source raster');results.reference={width:options.references[0].width,height:options.references[0].height,prompt};return new Promise(r=>{resolve=r;});};
 v.openImageGenerator(target);await wait(20);let el=v.imageDialog.contentEl;const ta=el.querySelector('.qc-image-prompt');ta.value='保留主体，将背景改成绿色';ta.dispatchEvent(new Event('input'));el.querySelector('.qc-image-submit').click();for(let i=0;!resolve&&i<150;i++)await wait(20);assert(resolve,'Edit did not start');for(let i=0;!el.querySelector('.qc-image-background')&&i<100;i++)await wait(20);el.querySelector('.qc-image-background').click();resolve({pictures:[edit],warnings:[],usage:{generated_images:1,total_tokens:10}});
 let job;for(let i=0;i<150;i++){job=[...p.imageJobs.jobs.values()].find(j=>j.path===file.path&&j.state==='ready');if(job)break;await wait(20);}assert(job,'Edit task not ready');p.openImageTasks();await wait(40);const row=[...document.querySelectorAll('.qc-image-task')].find(r=>r.querySelector('.qc-image-task-prompt')?.textContent===job.prompt);row.querySelector('button').click();for(let i=0;!document.querySelector('.qc-image-result-card')&&i<100;i++)await wait(20);el=document.querySelector('.qc-image-result-actions').closest('.qc-image-generate');
 assert(el.querySelectorAll('.qc-image-result-card').length===1,'No preview');assert(v.canvas.getObjects()[at]===target,'Preview changed source');results.previewPreservesOriginal=true;
 [...el.querySelectorAll('button')].find(b=>b.textContent==='替换原图').click();await wait(150);const changed=v.canvas.getObjects()[at];assert(changed!==target&&v.canvas.getObjects().length===n,'Replacement duplicated/removed unrelated objects');assert(changed.left===geometry.left&&changed.top===geometry.top&&changed.angle===geometry.angle&&changed.flipX===geometry.flip,'Transform changed');assert(Math.abs(changed.getScaledWidth()-geometry.width)<.01&&Math.abs(changed.getScaledHeight()-geometry.height)<.01,'Visible dimensions changed');assert(changed.cropX===40&&changed.cropY===15,'Crop not transformed');assert(!guard(),'Old target guard remained valid');results.geometryAndCropPreserved=true;
 await v.undo();assert(v.canvas.getObjects()[at].getSrc()===target.getSrc(),'Undo missing original');await v.redo();assert(v.canvas.getObjects()[at].getSrc()===changed.getSrc(),'Redo missing edit');await v.flush();await v.onLoadFile(file);await wait(80);assert(v.canvas.getObjects()[at].getSrc()===changed.getSrc(),'Saved edit missing');results.undoRedoSaved=true;
 const current=v.canvas.getObjects()[at];const stale=v.imageGuard(current);v.canvas.remove(current);assert(!stale(),'Deleted target accepted result');assert(!(await v.applyImageResult([edit],current,false,stale)),'Applied to deleted source');await v.undo();results.deletedSourceRejected=true;
 const base={...await picture(800,600,'#f0ebe4'),zIndex:0,size:'800x600'}, layer={...await picture(100,120,'#ad7957'),zIndex:1,name:'Fox',box:[200,100,400,340]};const before=v.canvas.getObjects().length;
 await v.applyImageResult([layer,base],undefined,true,v.imageGuard());const group=v.canvas.getActiveObject();assert(group.type==='group'&&group.getObjects().length===2,'Layers not restored as editable group');const children=group.getObjects();assert(children[1].getScaledWidth()===200&&children[1].getScaledHeight()===240,'Layer bounding box not applied');await v.undo();assert(v.canvas.getObjects().length===before,'Layer import not atomic');await v.redo();results.layersAtomicAndPositioned=true;
 const native=await picture(3200,1800,'#dbd4c7');await v.applyImageResult([native],undefined,false,v.imageGuard());assert(v.canvas.getActiveObject().width===3200,'High resolution output was shrunk');await v.undo();results.nativeResolutionPreserved=true;
 const count=v.canvas.getObjects().length;await v.applyImageResult([pic,edit],undefined,false,v.imageGuard());assert(v.canvas.getObjects().length===count+2,'Group image insert failed');await v.undo();assert(v.canvas.getObjects().length===count,'Group image insert not one undo');results.groupImportAtomic=true;
 const nestedGroup=v.canvas.getObjects().find(o=>o.type==='group'&&o.qcLayerGroup),nested=nestedGroup.getObjects()[1];nestedGroup.set({angle:27,scaleX:.9,scaleY:1.3});nestedGroup.setCoords();const nestedBox=nested.getBoundingRect(),nestedAt=nestedGroup.getObjects().indexOf(nested);v.canvas.setActiveObject(nested);assert(v.imageGuard(nested)(),'Nested image guard failed');await v.applyImageResult([edit],nested,false,v.imageGuard(nested));const replacement=nestedGroup.getObjects()[nestedAt],box=replacement.getBoundingRect();assert(['left','top','width','height'].every(k=>Math.abs(box[k]-nestedBox[k])<.01),'Nested replacement changed world geometry');assert(nestedGroup.getObjects().length===2,'Nested replacement damaged group');await v.undo();results.nestedReplacementPreserved=true;
 p.settings.language='en';v.imageModelId='seedream-host-fixture';v.openImageGenerator();await wait(20);el=v.imageDialog.contentEl;assert(el.textContent.includes('Generation options'),'English options missing');v.imageDialog.close();results.english=true;
 return {...results,file:file.path};
}finally{proto.images=images;p.settings.ai=JSON.parse(settings);p.settings.language=language;if(v.imageDialog)v.imageDialog.close();if(original){const leaf=app.workspace.getLeavesOfType('qiaomu-cover-design').find(l=>l.view.file?.path===original.path);if(leaf)await app.workspace.revealLeaf(leaf);}}
