const p=app.plugins.plugins['qiaomu-cover-design'],wait=ms=>new Promise(r=>setTimeout(r,ms)),assert=(x,m)=>{if(!x)throw Error(m)},until=async fn=>{for(let i=0;i<200&&!fn();i++)await wait(20);assert(fn(),'Timed out')};
const old=p.settings.assistant,language=p.settings.language,inputs=[];let mode='palette',release;
const palette={bg:'#210303',ink:'#fff5ed',sub:'#efd6cc',accent:'#ff2222',accentInk:'#ffffff'};
const unregister=p.registerAssistant({id:'selection-scope-qa',name:'Selection scope QA',run:async input=>{inputs.push(structuredClone(input));if(mode==='deferred'){await new Promise(r=>release=r);return {reply:'Changed all',ops:[{op:'recolor',target:'all',color:'#123abc'}]}}return {reply:'Changed whole palette',ops:[{op:'palette',palette}]}}});
try{
 p.settings.assistant='selection-scope-qa';p.settings.language='zh';await p.ensureFolder(p.settings.designFolder);const file=await app.vault.create(p.unique(p.settings.designFolder,'Selection scope QA '+Date.now(),'qcover'),JSON.stringify(p.initialDesign('minimal','只改选中元素','保留副标题',undefined,'xhs')));await p.openDesign(file);const v=p.activeCover();await until(()=>v.canvas&&!v.restoring);await app.workspace.revealLeaf(v.leaf);
 const c=v.canvas,title=c.getObjects().find(o=>o.qcRole==='title'),subtitle=c.getObjects().find(o=>o.qcRole==='subtitle');v.addSemanticShape('rect','#168855');const shape=c.getObjects().at(-1);v.sceneNodes();
 const state=o=>JSON.stringify(o.toObject()),bg=()=>JSON.stringify(v.design.bg);const initialBg=bg();c.setActiveObject(title);const otherBefore=c.getObjects().filter(o=>o!==title).map(o=>[o,state(o)]);await v.ask('改成红色');
 assert(title.fill==='#e11d2e','Selected title did not become requested red');assert(bg()===initialBg,'Selected recolour changed canvas background');assert(otherBefore.every(([o,s])=>state(o)===s),'Selected recolour changed an unselected layer');assert(inputs.length===0,'Simple selected recolour invoked model');
 // White must remain white; a readability pass must not recolour an unselected low-contrast subtitle.
 subtitle.set({fill:'#ffffff'});const subBefore=state(subtitle);await v.ask('改成白色');assert(title.fill==='#ffffff'&&state(subtitle)===subBefore,'Readability pass escaped selection');
 await v.selectLayers([title.qcId,shape.qcId]);assert(v.selectionLabel().includes('2'),'Multi-selection scope not shown');await v.ask('改为#12AB34');assert(title.fill==='#12ab34'&&shape.fill==='#12ab34'&&state(subtitle)===subBefore,'Multi-selection recolour incorrect');
 await v.selectLayers(shape.qcId);assert(v.selectionLabel(),'Shape selection invisible');await v.ask('变成蓝色');assert(shape.fill==='#2563eb'&&title.fill==='#12ab34','Shape edit affected text');
 await v.selectLayers(title.qcId);const beforeBlocked=JSON.stringify(v.currentDesign());mode='palette';await v.ask('让选中元素的色彩更温暖');assert(JSON.stringify(v.currentDesign())===beforeBlocked,'Model palette escaped selection');assert(v.chat.at(-1).warn?.length,'Scope rejection not explained');assert(inputs.slice(-2).every(i=>i.editScope.kind==='selection'&&i.editScope.ids.includes(title.qcId)),'Correction lost scope');
 // Changing the live selection during generation must not retarget the pending request.
 mode='deferred';const frozenLabel=v.selectionLabel();const count=inputs.length;const pending=v.ask('让这个元素更柔和一点');await until(()=>inputs.length>count&&release);c.setActiveObject(subtitle);v.refreshInspector(true);assert(v.selectionLabel()===frozenLabel,'Busy scope follows new selection');release();await pending;assert(title.fill==='#123abc'&&subtitle.fill==='#ffffff','Pending edit switched targets');
 // Deleted objects cannot be replaced by a new object reusing their scene ID.
 await v.selectLayers(shape.qcId);release=undefined;const n=inputs.length;const obsolete=v.ask('让选中的图形更柔和');await until(()=>inputs.length>n&&release);c.remove(shape);v.addSemanticShape('rect','#998877');const replacement=c.getObjects().at(-1);replacement.qcId=shape.qcId;mode='palette';release();await obsolete;assert(replacement.fill==='#998877','Deleted selection redirected to replacement');
 c.discardActiveObject();v.refreshInspector(true);assert(v.selectionLabel()===undefined,'Canvas scope did not return');mode='palette';await v.ask('把整体配色改成红色');assert(v.design.bg.color==='#210303','Canvas-wide palette did not work without selection');assert(inputs.at(-1).editScope.kind==='canvas','Unselected request got scoped');
 return {singleColourExact:true,unselectedLayersUnchanged:true,multiSelection:true,shapeScope:true,globalOpsBlocked:true,correctiveRetryScoped:true,pendingSelectionFrozen:true,deletedSelectionProtected:true,unselectedCanvasEdit:true,file:file.path};
}finally{release?.();unregister();p.settings.assistant=old;p.settings.language=language;await p.saveSettings()}
