// Real canvas contextmenu propagation, transparent PNG download, selected-element AI and nested layer operations.
const p=app.plugins.plugins['qiaomu-cover-design'],wait=ms=>new Promise(r=>setTimeout(r,ms)),assert=(x,m)=>{if(!x)throw Error(m);},until=async(fn)=>{for(let i=0;i<150&&!fn();i++)await wait(20);assert(fn(),'Timed out');};
const file=await p.createDesign('右键菜单 QA '+Date.now(),'minimal',undefined,'右键验收','xhs');await wait(150);const v=app.workspace.getLeavesOfType('qiaomu-cover-design').find(l=>l.view.file?.path===file.path).view;await until(()=>!v.restoring);const c=v.canvas;require('fs').rmSync('/tmp/qcover-selected-elements.png',{force:true});
c.clear();const a=v.addShape('rect');a.qcName='Menu red';a.set({left:100,top:200,width:180,height:100,scaleX:1,scaleY:1,strokeWidth:0,fill:'#ff0000'});a.setCoords();const b=v.addShape('rect');b.qcName='Menu blue';b.set({left:160,top:220,width:180,height:100,scaleX:1,scaleY:1,strokeWidth:0,fill:'#0000ff'});b.setCoords();const other=v.addShape('circle');other.qcName='Menu other';other.set({left:600,top:600});other.setCoords();c.discardActiveObject();v.changed();await v.flush();
const layers=()=>{v.rightTab='layers';v.refreshInspector(true);},row=name=>[...v.containerEl.querySelectorAll('.qc-layer')].find(r=>r.querySelector('.qc-layer-name')?.textContent===name),select=names=>{layers();names.forEach((n,i)=>row(n).dispatchEvent(new MouseEvent('click',{bubbles:true,ctrlKey:i>0})));};
const menuItem=text=>[...document.querySelectorAll('.menu-item')].find(e=>e.querySelector('.menu-item-title')?.textContent===text),open=async(obj)=>{const r=c.upperCanvasEl.getBoundingClientRect(),bb=obj.getBoundingRect(),z=c.getZoom();const coords={clientX:r.left+(bb.left+bb.width/2)*z,clientY:r.top+(bb.top+bb.height/2)*z,bubbles:true,cancelable:true,button:2};c.upperCanvasEl.dispatchEvent(new MouseEvent('mousedown',coords));c.upperCanvasEl.dispatchEvent(new MouseEvent('contextmenu',{clientX:r.left+(bb.left+bb.width/2)*z,clientY:r.top+(bb.top+bb.height/2)*z,bubbles:true,cancelable:true,button:2}));await until(()=>menuItem('AI 编辑'));c.upperCanvasEl.dispatchEvent(new MouseEvent('mouseup',coords));c.upperCanvasEl.dispatchEvent(new MouseEvent('auxclick',coords));await wait(700);assert(menuItem('AI 编辑'),'Menu closed after opening');};
select(['Menu red']);v.rightTab='design';v.refreshInspector(true);const action=v.containerEl.querySelector('.qc-selection-create button');assert(action.textContent==='用 AI 编辑','Inspector label wrong');const groupBody=v.containerEl.querySelector('.qc-group-body');assert(Math.abs(action.getBoundingClientRect().left-groupBody.getBoundingClientRect().left-parseFloat(getComputedStyle(groupBody).paddingLeft))<1,'AI button misaligned');
await open(a);for(const key of ['AI 编辑','下载选中内容（PNG）',v.t('front'),v.t('forward'),v.t('backward'),v.t('back'),v.t('renameLayers'),v.t('copyObj'),v.t('duplicate'),'锁定',v.t('remove')])assert(menuItem(key),`Context action absent: ${key}`);
menuItem('AI 编辑').click();await until(()=>v.imageDialog);assert(v.imageDialog.contentEl.querySelector('.qc-image-references img'),'Context AI has no selected reference');v.imageDialog.close();
// Exercise the production save-dialog writer with an isolated destination; no user dialog is opened by the fixture.
select(['Menu blue','Menu red']);await open(a);assert(c.getActiveObjects().length===2,'Right-click collapsed selected elements');
const remote=require('@electron/remote'),dialog=remote.dialog,descriptor=Object.getOwnPropertyDescriptor(dialog,'showSaveDialog'),destination='/tmp/qcover-selected-elements.png';let requested;
Object.defineProperty(dialog,'showSaveDialog',{configurable:true,value:async options=>{requested=options;return {canceled:false,filePath:destination};}});
try {menuItem('下载选中内容（PNG）').click();await until(()=>requested&&require('fs').existsSync(destination));assert(requested.defaultPath==='选中内容.png'&&requested.filters[0].extensions[0]==='png','Save dialog filename/filter wrong');}finally{Object.defineProperty(dialog,'showSaveDialog',descriptor);}
const png=remote.nativeImage.createFromPath(destination),size=png.getSize();assert(size.width===240&&size.height===120,`Selection PNG bounds wrong: ${JSON.stringify(size)}`);
const bitmap=png.toBitmap(),stride=size.width*4,pixel=(x,y)=>[...bitmap.slice(y*stride+x*4,y*stride+x*4+4)];assert(pixel(230,0)[3]===0,'PNG lost transparent corners');assert(pixel(100,50)[0]===255&&pixel(100,50)[2]===0,'Multi-select export reversed canvas stacking');assert(c.getActiveObjects().length===2,'Download cleared selection');
await v.flush();await open(a);menuItem(v.t('forward')).click();assert(c.getObjects().map(o=>o.qcName).join('|')==='Menu other|Menu red|Menu blue','Multi-select forward reversed stacking');await v.undo();assert(v.canvas.getObjects().map(o=>o.qcName).join('|')==='Menu red|Menu blue|Menu other','Layer order undo failed');
// Reacquire live objects after undo, then reorder and group within an existing editable group.
const canvas=v.canvas;select(['Menu red','Menu blue']);v.groupLayers();const group=canvas.getActiveObject();v.renameLayers([group],'Menu group');await v.flush();select(['Menu red']);const child=group.getObjects().find(o=>o.qcName==='Menu red'),world=child.calcTransformMatrix().slice();v.order('front');assert(group.getObjects().at(-1)===child,'Nested front did not reorder');assert(child.calcTransformMatrix().every((n,i)=>Math.abs(n-world[i])<.001),'Nested order shifted coordinates');
select(['Menu red','Menu blue']);const worlds=group.getObjects().map(o=>o.calcTransformMatrix());v.groupLayers();const nested=canvas.getActiveObject();assert(nested.qcLayerGroup&&group.getObjects().length===1&&nested.getObjects().length===2,'Nested grouping failed');assert(nested.getObjects().every((o,i)=>o.calcTransformMatrix().every((n,j)=>Math.abs(n-worlds[i][j])<.001)),'Nested grouping shifted coordinates');
v.canvas.discardActiveObject();v.canvas.setActiveObject(nested);v.toggleLock();v.rightTab='design';v.refreshInspector(true);await v.flush();
return {contextEventWorks:true,menuSurvivesReleaseAnd700ms:true,inspectorAligned:true,aiReference:true,multiSelectionPreserved:true,download:{path:destination,...size,transparent:true,canvasStacking:true},layerOrderUndo:true,nestedOrder:true,nestedGroup:true,file:file.path};
