// Selected text/shapes/group editing, foreground wait, explicit background and iterative results. No paid calls.
const p=app.plugins.plugins['qiaomu-cover-design'],wait=ms=>new Promise(r=>setTimeout(r,ms)),assert=(x,m)=>{if(!x)throw Error(m);},until=async(fn)=>{for(let i=0;i<200&&!fn();i++)await wait(20);assert(fn(),'Timed out');};
const oldAi=JSON.stringify(p.settings.ai),proto=Object.getPrototypeOf(p.ai),images=proto.images,oldFile=p.activeCover()?.file;
const file=await p.createDesign('选区 AI 创作 QA '+Date.now(),'minimal',undefined,'选区创作','xhs');await wait(150);const v=app.workspace.getLeavesOfType('qiaomu-cover-design').find(l=>l.view.file?.path===file.path).view;await until(()=>!v.restoring);
const c=document.createElement('canvas');c.width=300;c.height=150;c.getContext('2d').fillStyle='#285dc7';c.getContext('2d').fillRect(0,0,300,150);const blob=await new Promise(r=>c.toBlob(r,'image/png')),pic={data:await blob.arrayBuffer(),type:'image/png'};
let resolve,reject,sent;const mock=()=>{resolve=reject=undefined;proto.images=(prompt,w,h,options)=>{sent=options;return new Promise((r,j)=>{resolve=r;reject=j;});};};
const layers=()=>{v.rightTab='layers';v.layerQuery='';v.refreshInspector(true);},row=name=>[...v.containerEl.querySelectorAll('.qc-layer')].find(r=>r.querySelector('.qc-layer-name')?.textContent===name),select=(names)=>{layers();names.forEach((name,i)=>row(name).dispatchEvent(new MouseEvent('click',{bubbles:true,ctrlKey:i>0})));};
const result=()=>document.querySelector('.qc-image-result-actions')?.closest('.qc-image-generate'),button=(el,text)=>[...el.querySelectorAll('button')].find(b=>b.textContent===text),closeResults=()=>document.querySelector('.qc-image-generate-modal .modal-header-button')?.click();
try{
 p.settings.ai.enabled=true;p.settings.ai.images.push({id:'selection-fixture',snap:{imageOn:true,imageEngine:'ark',imageBaseUrl:'https://fixture.invalid',imageKey:'fixture',imageModel:'doubao-seedream-5-0-260128',imageSize:'auto'}});v.imageModelId='selection-fixture';
 v.canvas.clear();const a=v.addShape('rect');a.qcName='Alpha';a.set({left:100,top:150,width:180,height:90,scaleX:1,scaleY:1,fill:'#c23a34',angle:13});a.setCoords();const b=v.addText('编辑文字',{size:40});b.qcName='Beta';b.set({left:340,top:190,width:220});b.setCoords();const other=v.addShape('circle');other.qcName='Other';v.canvas.discardActiveObject();v.changed();await v.flush();select(['Alpha','Beta']);
 const originalCount=v.canvas.getObjects().length;await v.openSelectionImageGenerator();let el=v.imageDialog.contentEl;assert(el.querySelector('.qc-image-prompt-picker'),'Compact prompt picker missing');assert(!el.querySelector('.qc-image-presets'),'Expanded prompts still shown');assert(getComputedStyle(el.querySelector('.qc-image-advanced')).borderTopWidth==='0px','Extra divider remains');assert(el.querySelector('.qc-image-references img'),'Selection preview missing');const selection=v.imageDialog.context.selection;assert(selection.objects.length===2,'Multi-selection not captured');assert(await v.selectionMatches(selection),'Snapshot already stale');
 const prompt=el.querySelector('.qc-image-prompt');prompt.value='将所选内容改为柔和纸艺';prompt.dispatchEvent(new Event('input'));mock();el.querySelector('.qc-image-submit').click();await until(()=>!!resolve&&!!el.querySelector('.qc-image-background'));assert(v.imageDialog&&getComputedStyle(el.querySelector('.qc-image-form')).display==='none','Generation did not stay open');assert(getComputedStyle(el.querySelector('.qc-image-waiting')).display!=='none','No waiting state');assert(sent.references.length===1,'Selected elements not combined');resolve({pictures:[pic],warnings:[]});await until(()=>!!result());el=result();assert(v.canvas.getObjects().length===originalCount,'Preview replaced originals');assert(button(el,'替换所选元素'),'Replace selection action missing');assert(button(el,'继续创作'),'Continue action missing');
 button(el,'继续创作').click();await until(()=>!!v.imageDialog);el=v.imageDialog.contentEl;assert(el.querySelector('.qc-image-previous').textContent.includes('柔和纸艺'),'Continuation lost history');assert(!el.querySelector('.qc-image-prompt').value&&el.querySelector('.qc-image-submit').disabled,'Continuation should await a new instruction');const nextPrompt=el.querySelector('.qc-image-prompt');nextPrompt.value='进一步增加纸张纹理';nextPrompt.dispatchEvent(new Event('input'));const reference=v.imageDialog.context.reference;assert(reference.width===300&&reference.height===150,'Continuation did not use result pixels');mock();el.querySelector('.qc-image-submit').click();await until(()=>!!resolve);resolve({pictures:[pic],warnings:[]});await until(()=>!!result());el=result();button(el,'替换所选元素').click();await until(()=>!el.isConnected);assert(v.canvas.getObjects().length===originalCount-1,'Selection replacement did not preserve unrelated elements');assert(v.canvas.getObjects().some(o=>o.qcName==='Other'),'Unrelated layer lost');const replacement=v.canvas.getActiveObject(),box=replacement.getBoundingRect();assert(['left','top','width','height'].every(k=>Math.abs(box[k]-selection.box[k])<.02),'Replacement shifted selection bounds');await v.undo();assert(v.canvas.getObjects().some(o=>o.text==='编辑文字'),'Undo did not restore editable text');await v.redo();await v.flush();await v.onLoadFile(file);await until(()=>!v.restoring);assert(v.canvas.getObjects().length===2,'Replacement lost on reopen');// Reload resets history; start a separate editable fixture for nested replacement.
 // A second capture checks durable guards and nested group replacement independently.
 v.canvas.clear();const x=v.addShape('rect');x.qcName='First';const y=v.addShape('circle');y.qcName='Second';v.canvas.discardActiveObject();v.changed();select(['First','Second']);v.groupLayers();const group=v.canvas.getActiveObject();group.qcName='Parent';group.set({angle:23,scaleX:.8,scaleY:1.3});group.setCoords();v.changed();await v.flush();select(['First','Second']);await v.openSelectionImageGenerator();const nested=v.imageDialog.context.selection;v.imageDialog.close();await v.flush();await v.onLoadFile(file);await until(()=>!v.restoring);assert(await v.selectionMatches(nested),'Selection guard failed after reopen');await v.replaceImageSelection(pic,nested,v.imageGuard());const parent=v.canvas.getObjects()[0];assert(parent.getObjects().length===1,'Nested replacement flattened parent');const nestedImage=parent.getObjects()[0],matrix=nestedImage.calcTransformMatrix(),expected=[nested.box.width/nestedImage.width,0,0,nested.box.height/nestedImage.height,nested.box.left+nested.box.width/2,nested.box.top+nested.box.height/2];assert(matrix.every((n,i)=>Math.abs(n-expected[i])<.02),'Nested replacement changed its rendered world transform');await v.undo();assert(v.canvas.getObjects()[0].getObjects().length===2,'Nested replacement undo failed');
 const obj=v.selectionObjects(nested)[0];obj.set({fill:'#112233'});v.changed();let refused=false;try{await v.replaceImageSelection(pic,nested,v.imageGuard());}catch{refused=true;}assert(refused,'Changed original was replaced');
 // Failures remain in the same form with the draft and require a new explicit click.
 v.canvas.discardActiveObject();v.openImageGenerator();el=v.imageDialog.contentEl;const ta=el.querySelector('.qc-image-prompt');ta.value='失败后保留草稿';ta.dispatchEvent(new Event('input'));mock();el.querySelector('.qc-image-submit').click();await until(()=>!!reject);reject(Error('QA controlled failure'));await until(()=>getComputedStyle(el.querySelector('.qc-image-form')).display!=='none');assert(v.imageDialog&&ta.value==='失败后保留草稿','Failure lost dialog or draft');v.imageDialog.close();
 return {file:file.path,compactPrompts:true,foregroundWait:true,automaticResults:true,selectedReference:true,iterativeReference:true,previewNoMutation:true,replaceUndoSave:true,nestedWorldBounds:true,guardSurvivesReopen:true,changedOriginalRefused:true,failureKeepsDraft:true};
}finally{proto.images=images;p.settings.ai=JSON.parse(oldAi);v.imageDialog?.close();closeResults();if(oldFile)await p.openDesign(oldFile);}
