/** Generated by scripts/build-font-library.py. Do not edit by hand. */
import type { BundledFont } from './fonts';
export const FONT_LIBRARY_VERSION = '1.0.0';
export const FONT_LIBRARY_REPO = 'joeseesun/qiaomu-cover-fonts';
export const BUNDLED_FONTS: BundledFont[] = [
 {
  "id": "notosans",
  "family": "思源黑体",
  "en": "Noto Sans SC",
  "mood": "sans",
  "roles": [
   "body"
  ],
  "zh": "标准黑体，屏显清晰，最稳的正文和说明文字",
  "hint": "通用 · 正文",
  "file": "notosans.woff2",
  "bytes": 1263476,
  "sha256": "3ca125c45785eab24bdcd4d4039431479fef196c3aa9913fed4b0f255336101f",
  "cjk": true,
  "priority": 1,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/noto/specimen/Noto+Sans+SC",
  "coverage": 8105
 },
 {
  "id": "notosans-bold",
  "family": "思源黑体 Bold",
  "en": "Noto Sans SC Bold",
  "mood": "sans",
  "roles": [
   "title",
   "body"
  ],
  "zh": "思源黑体粗体，稳重的标题和强调",
  "hint": "标题 · 稳重",
  "file": "notosans-bold.woff2",
  "bytes": 1294524,
  "sha256": "0e7e551d15e71a354679130765b7d45d4225a1eb46a995f08ad1c101d9ff3ad3",
  "cjk": true,
  "priority": 1,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/noto/specimen/Noto+Sans+SC",
  "coverage": 8105
 },
 {
  "id": "notosans-heavy",
  "family": "思源黑体 Heavy",
  "en": "Noto Sans SC Black",
  "mood": "sans",
  "roles": [
   "title"
  ],
  "zh": "思源黑体最粗一档，干货、清单、大字报式冲击",
  "hint": "干货 · 冲击",
  "file": "notosans-heavy.woff2",
  "bytes": 1237428,
  "sha256": "6fb124c8f2fea5b626b3fc0fc8d531a0d85bc99adbb09ec28efe06f0ac8b94b8",
  "cjk": true,
  "priority": 1,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/noto/specimen/Noto+Sans+SC",
  "coverage": 8105
 },
 {
  "id": "notoserif",
  "family": "思源宋体",
  "en": "Noto Serif SC",
  "mood": "serif",
  "roles": [
   "body"
  ],
  "zh": "简体中文最好的开源明朝体，正文与副标题",
  "hint": "通用 · 编辑",
  "file": "notoserif.woff2",
  "bytes": 1662732,
  "sha256": "de134adb512429992d47096d5e5d94d0488d3890f4e9a592aaabcf4fc6fb3355",
  "cjk": true,
  "priority": 2,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/noto/specimen/Noto+Serif+SC",
  "coverage": 8105
 },
 {
  "id": "notoserif-bold",
  "family": "思源宋体 Bold",
  "en": "Noto Serif SC Bold",
  "mood": "serif",
  "roles": [
   "title",
   "body"
  ],
  "zh": "思源宋体粗体，严肃、权威的标题",
  "hint": "标题 · 编辑",
  "file": "notoserif-bold.woff2",
  "bytes": 1715756,
  "sha256": "d08e531b6e2476d6a68307f6b0c0144da650491889cf814679c34d2f9fd168c5",
  "cjk": true,
  "priority": 2,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/noto/specimen/Noto+Serif+SC",
  "coverage": 8105
 },
 {
  "id": "notoserif-heavy",
  "family": "思源宋体 Heavy",
  "en": "Noto Serif SC Black",
  "mood": "serif",
  "roles": [
   "title"
  ],
  "zh": "最粗的宋体，杂志封面与深度长文的大标题",
  "hint": "杂志 · 深度",
  "file": "notoserif-heavy.woff2",
  "bytes": 1580648,
  "sha256": "729c42f795041ba47f794be1729e6d515b51f73d9baf2085c5b0941e30e6bfb3",
  "cjk": true,
  "priority": 1,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/noto/specimen/Noto+Serif+SC",
  "coverage": 8105
 },
 {
  "id": "zhuque",
  "family": "朱雀仿宋",
  "en": "Zhuque Fangsong",
  "mood": "serif",
  "roles": [
   "title",
   "body"
  ],
  "zh": "开源仿宋，清瘦克制有书卷气",
  "hint": "文化 · 书籍 · 典雅",
  "file": "zhuque.woff2",
  "bytes": 3225112,
  "sha256": "8a57c5cdff207715cc3f7bc248e7ab9b478f6e7f49408d0ef77ad55b4d3ab0b5",
  "cjk": true,
  "priority": 2,
  "license": "OFL-1.1",
  "home": "https://github.com/TrionesType/zhuque",
  "coverage": 8105
 },
 {
  "id": "wenkai",
  "family": "霞鹜文楷",
  "en": "LXGW WenKai",
  "mood": "serif",
  "roles": [
   "title",
   "body"
  ],
  "zh": "现代感的开源楷体，有手写温度但不土",
  "hint": "生活 · 读书 · 温暖",
  "file": "wenkai.woff2",
  "bytes": 1900132,
  "sha256": "9008f65301f398ee544c751e0b16b23026e612480644c159c58401e7c97db24b",
  "cjk": true,
  "priority": 2,
  "license": "OFL-1.1",
  "home": "https://github.com/lxgw/LxgwWenKai",
  "coverage": 8105
 },
 {
  "id": "smiley",
  "family": "得意黑",
  "en": "Smiley Sans",
  "mood": "display",
  "roles": [
   "title"
  ],
  "zh": "自带速度感的斜体黑，开源字体里最有设计签名的一款",
  "hint": "科技 · 潮流 · 产品",
  "file": "smiley.woff2",
  "bytes": 1107764,
  "sha256": "776d4c0dddac43638554e7303f6f0187338e4b5ba0501216a5ec6bb14c655f6d",
  "cjk": true,
  "priority": 1,
  "license": "OFL-1.1",
  "home": "https://github.com/atelier-anchor/smiley-sans",
  "coverage": 8105
 },
 {
  "id": "douyin",
  "family": "抖音美好体",
  "en": "Douyin Sans",
  "mood": "display",
  "roles": [
   "title"
  ],
  "zh": "字节跳动开源的粗黑，带一点圆润的现代感",
  "hint": "短视频 · 年轻 · 种草",
  "file": "douyin.ttf",
  "bytes": 1919404,
  "sha256": "fbecfacdfac33982774e301073a8d357a09c698cd3134bb6ddec0f5bfc268fa1",
  "cjk": true,
  "priority": 1,
  "license": "OFL-1.1",
  "home": "https://github.com/bytedance/fonts",
  "coverage": 6638
 },
 {
  "id": "glow",
  "family": "未来荧黑",
  "en": "Glow Sans SC Heavy",
  "mood": "display",
  "roles": [
   "title"
  ],
  "zh": "几何骨架的重黑体，科技、发布会、数据结论",
  "hint": "科技 · 未来 · 发布会",
  "file": "glow.woff2",
  "bytes": 1826500,
  "sha256": "c12d4668a33019c757a9ec2c6d7fc43629189a8d5e8636d9bb38c3936020684c",
  "cjk": true,
  "priority": 2,
  "license": "OFL-1.1",
  "home": "https://github.com/welai/glow-sans",
  "coverage": 8105
 },
 {
  "id": "huangyou",
  "family": "站酷庆科黄油体",
  "en": "ZCOOL QingKe HuangYou",
  "mood": "display",
  "roles": [
   "title"
  ],
  "zh": "圆润饱满，有招牌字的亲和力",
  "hint": "种草 · 促销 · 亲切",
  "file": "huangyou.woff2",
  "bytes": 1742972,
  "sha256": "a15d7e72cd7ad20b67ecf6adf46d08bab5764ea700ec8fae7cc29055e9cb9fbc",
  "cjk": true,
  "priority": 2,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/ZCOOL+QingKe+HuangYou",
  "coverage": 6722
 },
 {
  "id": "kuaile",
  "family": "站酷快乐体",
  "en": "ZCOOL KuaiLe",
  "mood": "display",
  "roles": [
   "title"
  ],
  "zh": "活泼但不幼稚",
  "hint": "轻松 · 美食 · 亲子",
  "file": "kuaile.woff2",
  "bytes": 855692,
  "sha256": "19d11b1154b2e5f37371d7be9640dbae97d06fbf2331cb5fc257ae5f813ea5e8",
  "cjk": true,
  "priority": 3,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/ZCOOL+KuaiLe",
  "coverage": 6640
 },
 {
  "id": "jiangcheng",
  "family": "江城圆体",
  "en": "JiangCheng YuanTi",
  "mood": "display",
  "roles": [
   "title",
   "body"
  ],
  "zh": "完成度最高的开源圆体，温和亲切",
  "hint": "圆体 · 生活 · 母婴",
  "file": "jiangcheng.woff2",
  "bytes": 1565164,
  "sha256": "0be9728fe58f3c69ad93a2a952ab0e78089873f06ebe80110b67664ffa22cbdc",
  "cjk": true,
  "priority": 2,
  "license": "OFL-1.1",
  "home": "https://www.npmjs.com/package/@fontpkg/jiang-cheng-yuan-ti",
  "coverage": 7836
 },
 {
  "id": "maoken",
  "family": "猫啃什锦黑",
  "en": "Maoken Assorted Sans",
  "mood": "display",
  "roles": [
   "title"
  ],
  "zh": "圆头圆脑的粗标题字，俏皮有记忆点",
  "hint": "种草 · 美食 · 俏皮",
  "file": "maoken.woff2",
  "bytes": 1655936,
  "sha256": "5755a50744e7df367f957a0044587bcdcce4dd2134cf7ec0fe583635a851c6af",
  "cjk": true,
  "priority": 3,
  "license": "OFL-1.1",
  "home": "https://github.com/maoken-fonts/MaokenAssortedSans",
  "coverage": 8105
 },
 {
  "id": "tiejili",
  "family": "铁蒺藜体",
  "en": "Tiejili SC",
  "mood": "display",
  "roles": [
   "title"
  ],
  "zh": "棱角锋利的粗体，国潮、热血、武侠",
  "hint": "国潮 · 热血 · 力量",
  "file": "tiejili.woff2",
  "bytes": 1496920,
  "sha256": "25f8a847d9adb44734fdca39cf9465c981cb5189273117f590246956935312b6",
  "cjk": true,
  "priority": 3,
  "license": "OFL-1.1",
  "home": "https://github.com/Buernia/Tiejili",
  "coverage": 8105
 },
 {
  "id": "mashan",
  "family": "马善政楷书",
  "en": "Ma Shan Zheng",
  "mood": "brush",
  "roles": [
   "title"
  ],
  "zh": "毛笔楷书，笔画清楚，缩略图里也认得出",
  "hint": "国风 · 书法 · 节气",
  "file": "mashan.woff2",
  "bytes": 3233640,
  "sha256": "9bb3130d1b7e752e1df902891a41c7aeb5b94697951acf54eec60b954d7a1cb2",
  "cjk": true,
  "priority": 3,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Ma+Shan+Zheng",
  "coverage": 6638
 },
 {
  "id": "zhimang",
  "family": "志莽行书",
  "en": "Zhi Mang Xing",
  "mood": "brush",
  "roles": [
   "title"
  ],
  "zh": "潇洒的行书，金句和情绪",
  "hint": "行书 · 励志 · 金句",
  "file": "zhimang.woff2",
  "bytes": 2288372,
  "sha256": "63688c12c559f3ba1447e32ba8ba561eb06a2cfaaf9dc1db5126b217825be108",
  "cjk": true,
  "priority": 3,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Zhi+Mang+Xing",
  "coverage": 6638
 },
 {
  "id": "pixel",
  "family": "缝合像素字体",
  "en": "Fusion Pixel",
  "mood": "display",
  "roles": [
   "title"
  ],
  "zh": "像素风，游戏与复古",
  "hint": "像素 · 游戏 · 复古",
  "file": "pixel.woff2",
  "bytes": 251944,
  "sha256": "c9193b3b500ec237fff9e437c72df2c4195ae4cdddbfeee18655b47ef70aad60",
  "cjk": true,
  "priority": 3,
  "license": "OFL-1.1",
  "home": "https://github.com/TakWolf/fusion-pixel-font",
  "coverage": 6042
 },
 {
  "id": "inter",
  "family": "Inter",
  "en": "Inter",
  "mood": "sans",
  "roles": [
   "body",
   "tag"
  ],
  "zh": "干净的通用无衬线，英文副标题与界面感",
  "hint": "通用 · 干净",
  "file": "inter.woff2",
  "bytes": 24980,
  "sha256": "47084ea0d235fbca0b0c5ec663969a906daaeb667fd5f191007ec5c80b62ed5c",
  "cjk": false,
  "priority": 2,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Inter"
 },
 {
  "id": "inter-bold",
  "family": "Inter Bold",
  "en": "Inter ExtraBold",
  "mood": "sans",
  "roles": [
   "title",
   "number"
  ],
  "zh": "Inter 的粗体，英文标题与数字",
  "hint": "标题 · 现代",
  "file": "inter-bold.woff2",
  "bytes": 25808,
  "sha256": "d12a4723b63d6f0369e5d56bea8fa948fc36bbb9fa92b1bf3b76fb399a19c249",
  "cjk": false,
  "priority": 2,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Inter"
 },
 {
  "id": "spacegrotesk",
  "family": "Space Grotesk",
  "en": "Space Grotesk",
  "mood": "sans",
  "roles": [
   "title",
   "number",
   "tag"
  ],
  "zh": "科技感无衬线，配未来荧黑",
  "hint": "科技 · 产品",
  "file": "spacegrotesk.woff2",
  "bytes": 15600,
  "sha256": "8c3d72df71f151bd549c89d78b146858c25e4d16d3a3bfe79bf93bf37ee2c9ae",
  "cjk": false,
  "priority": 2,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Space+Grotesk"
 },
 {
  "id": "bricolage",
  "family": "Bricolage Grotesque",
  "en": "Bricolage Grotesque",
  "mood": "display",
  "roles": [
   "title",
   "number",
   "tag"
  ],
  "zh": "有个性的怪诞体，潮流与创作者话题",
  "hint": "潮流 · 创作者",
  "file": "bricolage.woff2",
  "bytes": 23388,
  "sha256": "305c50946ce47c91fab0ea161bdd92a3d21dade9699e48000a64ff59cafe40d5",
  "cjk": false,
  "priority": 2,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Bricolage+Grotesque"
 },
 {
  "id": "unbounded",
  "family": "Unbounded",
  "en": "Unbounded",
  "mood": "display",
  "roles": [
   "title",
   "number"
  ],
  "zh": "宽体几何，发布会和未来感",
  "hint": "发布会 · 未来",
  "file": "unbounded.woff2",
  "bytes": 26596,
  "sha256": "2856ccff50a8dcb18a34d68c996d9894181d7d506aaa1534f9b9c99d0939c0c3",
  "cjk": false,
  "priority": 3,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Unbounded"
 },
 {
  "id": "anton",
  "family": "Anton",
  "en": "Anton",
  "mood": "display",
  "roles": [
   "title",
   "number"
  ],
  "zh": "窄粗体，YouTube 缩略图标配",
  "hint": "缩略图 · 冲击",
  "file": "anton.woff2",
  "bytes": 19460,
  "sha256": "5aa51ca1a8d65846f52724d0e3c6f728347f19df1f4ee88acde613ef403f50c1",
  "cjk": false,
  "priority": 1,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Anton"
 },
 {
  "id": "bebas",
  "family": "Bebas Neue",
  "en": "Bebas Neue",
  "mood": "display",
  "roles": [
   "number",
   "tag"
  ],
  "zh": "全大写窄体，数字、期号、角标",
  "hint": "数字 · 角标",
  "file": "bebas.woff2",
  "bytes": 15428,
  "sha256": "83baf2705cd75f7047e8d11dc9aceeb4ee50407a72f1981937b0b909227b1e68",
  "cjk": false,
  "priority": 1,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Bebas+Neue"
 },
 {
  "id": "archivoblack",
  "family": "Archivo Black",
  "en": "Archivo Black",
  "mood": "display",
  "roles": [
   "title"
  ],
  "zh": "厚重有力的英文标题",
  "hint": "冲击 · 标题",
  "file": "archivoblack.woff2",
  "bytes": 26144,
  "sha256": "04b4a5cc289e3d9fb47ee5ba315361a0afb9db57d93424948c039c9205214c8e",
  "cjk": false,
  "priority": 3,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Archivo+Black"
 },
 {
  "id": "dmserif",
  "family": "DM Serif Display",
  "en": "DM Serif Display",
  "mood": "serif",
  "roles": [
   "title"
  ],
  "zh": "优雅的展示衬线",
  "hint": "优雅 · 生活方式",
  "file": "dmserif.woff2",
  "bytes": 27692,
  "sha256": "c0652f22903b1a547ad50495aa3f5314e4f666e34921e9e953e3f545fdde14ba",
  "cjk": false,
  "priority": 3,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/DM+Serif+Display"
 },
 {
  "id": "fraunces",
  "family": "Fraunces",
  "en": "Fraunces",
  "mood": "serif",
  "roles": [
   "title",
   "number"
  ],
  "zh": "柔和有温度的衬线，配霞鹜文楷",
  "hint": "温暖 · 人文",
  "file": "fraunces.woff2",
  "bytes": 21728,
  "sha256": "4126e9c07ed4338f458484701e1df4135aca776e0730c780ecf9eff1f627319e",
  "cjk": false,
  "priority": 2,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Fraunces"
 },
 {
  "id": "instrument",
  "family": "Instrument Serif",
  "en": "Instrument Serif",
  "mood": "serif",
  "roles": [
   "title",
   "number",
   "tag"
  ],
  "zh": "当下最流行的编辑衬线",
  "hint": "编辑 · 杂志",
  "file": "instrument.woff2",
  "bytes": 22704,
  "sha256": "c488bd06cd1fafaf120ef24d0a857c55c8646b5de2badc4e709f4b87f2971920",
  "cjk": false,
  "priority": 1,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Instrument+Serif"
 },
 {
  "id": "instrument-italic",
  "family": "Instrument Serif Italic",
  "en": "Instrument Serif Italic",
  "mood": "serif",
  "roles": [
   "tag",
   "number"
  ],
  "zh": "编辑斜体，杂志感角标与期号",
  "hint": "编辑 · 角标",
  "file": "instrument-italic.woff2",
  "bytes": 23892,
  "sha256": "ce40e4eb5696b0270f39325326c55162eaa849c0a24fc0cd79bc1f14de8a95af",
  "cjk": false,
  "priority": 1,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Instrument+Serif"
 },
 {
  "id": "cormorant",
  "family": "Cormorant Garamond",
  "en": "Cormorant Garamond",
  "mood": "serif",
  "roles": [
   "title",
   "tag"
  ],
  "zh": "高级、奢侈品、香氛",
  "hint": "高级 · 奢华",
  "file": "cormorant.woff2",
  "bytes": 25128,
  "sha256": "cd35b0a6123f591fd3ee5733e0c2d2a33b258b36194b5c1a13c68f9cbe5f0d1e",
  "cjk": false,
  "priority": 3,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Cormorant+Garamond"
 },
 {
  "id": "jetbrains",
  "family": "JetBrains Mono",
  "en": "JetBrains Mono",
  "mood": "mono",
  "roles": [
   "tag",
   "number"
  ],
  "zh": "代码、教程、工具类封面的标签",
  "hint": "代码 · 教程",
  "file": "jetbrains.woff2",
  "bytes": 22516,
  "sha256": "1d5b5738120473ecb0d758290426d6d4b59873b7f3d4608541989cd0ab5452e3",
  "cjk": false,
  "priority": 2,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/JetBrains+Mono"
 },
 {
  "id": "caveat",
  "family": "Caveat",
  "en": "Caveat",
  "mood": "brush",
  "roles": [
   "tag"
  ],
  "zh": "手写批注，配合荧光笔效果",
  "hint": "手写 · 笔记",
  "file": "caveat.woff2",
  "bytes": 53700,
  "sha256": "47f727b99caf2969308014487a9bcf4909c20cae52583d472ae42cc62fdd04b4",
  "cjk": false,
  "priority": 3,
  "license": "OFL-1.1",
  "home": "https://fonts.google.com/specimen/Caveat"
 }
];
